// ---------------------------------------------------------------------------
// Lesson prose.
//
// The authored explanation for each lesson, moved verbatim from the previous
// build's i18n table. This is CONTENT, not copy I wrote: the wording, the
// examples and the emphasis are the product's actual teaching, and a
// migration is not licence to rewrite it.
//
// `intro` is the opening explanation; `deeper` is the "worth knowing" block
// that adds nuance. Both are shown in full — the collapse control that used
// to hide `deeper` was removed, because it added a click for no benefit.
//
// `extra`, where present, is DIFFERENT: it is new content, added on request
// after auditing every lesson's quiz questions against what that lesson
// actually teaches. Four lessons quizzed on something never defined
// anywhere in their own prose — l0 tested ETFs and market cap without
// defining either; l4 tested what a hammer or bullish-engulfing candle
// looks like without ever describing either shape; l6 tested RSI
// divergence, never mentioned; l7 tested a double bottom's structure,
// never described. `intro`/`deeper` were left exactly as they were — this
// is additive, not a rewrite of the authored text above it.
// ---------------------------------------------------------------------------
import type { Localized } from '@core/types/kb';

export interface LessonProse {
  intro: Localized;
  deeper: Localized;
  extra?: Localized;
}

export const LESSON_PROSE: Record<string, LessonProse> = {
  l0: {
    intro: { en: "Every lesson after this one assumes you already know what a stock is, what actually moves its price, and why we're even looking at charts in the first place. This page covers that groundwork in plain language, once, so the rest of the site can focus on charts.", he: 'כל שיעור אחרי הדף הזה מניח שאתם כבר יודעים מה זו מניה, מה באמת מזיז את המחיר שלה, ולמה בכלל מסתכלים על גרפים מלכתחילה. הדף הזה מכסה את הבסיס הזה בשפה פשוטה, פעם אחת, כדי שכל שאר האתר יוכל להתמקד בגרפים.' },
    deeper: { en: "Everything on this site is taught using stocks, but technical analysis isn't just for stocks. The same tools — support, resistance, trends, candlesticks, RSI — are used almost identically on crypto, forex, commodities, and indices, because they all come down to the same thing: a chart of buyers and sellers agreeing on a price over time.", he: 'כל מה שבאתר הזה מלמד באמצעות מניות, אבל ניתוח טכני הוא לא רק למניות. אותם הכלים — תמיכה, התנגדות, מגמות, נרות, RSI — משמשים כמעט באופן זהה בקריפטו, מט"ח, סחורות ומדדים, כי כולם בסופו של דבר אותו דבר: גרף של קונים ומוכרים שמסכימים על מחיר לאורך זמן.' },
    extra: { en: "Two terms worth having before the rest of the site uses them: an ETF is a fund that trades like a single stock but actually holds dozens or hundreds of companies at once, so buying one unit spreads your money across everything inside it instead of depending on one company's fate. And a company's market cap is its share price multiplied by the number of shares outstanding — the standard way to compare company \"size\", even when the share prices themselves look completely different. A couple more: the ticker is the short code that identifies a stock on an exchange — the marketplace where shares actually change hands, like the NYSE or the Tel Aviv Stock Exchange. And a dividend is a slice of a company's profit paid out to shareholders in cash, usually on a regular schedule — not every company pays one.", he: 'שני מושגים ששווה להכיר לפני שאר האתר משתמש בהם: קרן סל (ETF) היא קרן שנסחרת כמו מניה בודדת אבל מחזיקה בפועל עשרות או מאות חברות בבת אחת, כך שקנייה של יחידה אחת מפזרת את הכסף על פני כל מה שבתוכה, במקום להיות תלויה בגורל של חברה אחת. ושווי שוק של חברה הוא מחיר המניה כפול מספר המניות במחזור — הדרך המקובלת להשוות "גודל" בין חברות, גם כשמחירי המניות עצמם נראים שונים לחלוטין. עוד כמה: הסימול הוא הקוד הקצר שמזהה מניה בבורסה — הזירה שבה מניות בפועל עוברות יד, כמו NYSE או הבורסה לניירות ערך בתל אביב. ודיבידנד הוא חלק מרווחי החברה שמשולם לבעלי המניות במזומן, בדרך כלל במועדים קבועים — לא כל חברה מחלקת דיבידנד.' }
  },
  l1: {
    intro: { en: 'Support is a price area where buying pressure has repeatedly overwhelmed selling pressure in the past — not a hard floor, just a zone worth watching. Look at the chart below before reading the panel on the right.', he: 'תמיכה היא אזור מחיר שבו לחץ קנייה גבר שוב ושוב על לחץ מכירה בעבר — לא רצפה קשיחה, אלא אזור ששווה לעקוב אחריו. הסתכלו על הגרף למטה לפני קריאת הפאנל מימין.' },
    deeper: { en: 'Every time a level holds, more traders notice it and place orders around it — which is part of what makes it hold again next time. But that same crowding is also why levels eventually break: once price finally pushes through, all the stop-losses clustered just beyond it get triggered at once, which is often exactly what fuels the strength of a breakout.', he: 'בכל פעם שרמה מחזיקה, יותר סוחרים שמים לב אליה ומציבים סביבה פקודות — וזה חלק ממה שגורם לה להחזיק שוב בפעם הבאה. אבל אותה צפיפות היא גם הסיבה שרמות בסופו של דבר נשברות: ברגע שהמחיר סוף סוף פורץ דרך, כל אותם סטופ-לוס שהצטברו ממש מעבר לרמה מופעלים בבת אחת — מה שלעיתים קרובות בדיוק מזין את עוצמת הפריצה.' }
  },
  l2: {
    intro: { en: 'A breakout is price closing decisively above a resistance zone. A retest is when price returns to that same zone afterward — often turning former resistance into new support — before continuing. Watch how volume behaves at the breakout candle.', he: 'פריצה היא כאשר המחיר נסגר בבירור מעל אזור התנגדות. ריטסט (בדיקה חוזרת) הוא כאשר המחיר חוזר לאותו אזור לאחר מכן — ולעיתים קרובות הופך התנגדות ישנה לתמיכה חדשה — לפני שהוא ממשיך. שימו לב איך הנפח מתנהג בנר הפריצה.' },
    deeper: { en: "Not every dip after a breakout is a retest — sometimes it's a full reversal. The distinction traders look for: a genuine retest usually pauses close to the old resistance and doesn't spend more than a candle or two trading back below it. A close that stays under the old level for longer than that is a warning the breakout may be failing.", he: 'לא כל ירידה אחרי פריצה היא ריטסט — לפעמים זה היפוך מלא. ההבחנה שסוחרים מחפשים: ריטסט אמיתי בדרך כלל נעצר בקרבת ההתנגדות הישנה ולא נשאר יותר מנר אחד או שניים מתחתיה. סגירה שנשארת מתחת לרמה הישנה לזמן ארוך יותר היא אזהרה שהפריצה עלולה להיכשל.' }
  },
  l3: {
    intro: { en: 'A moving average is the average closing price over a fixed number of past sessions, recalculated every day. Shorter averages react faster; longer averages describe the broader trend. Toggle them on and off to see what each one is actually showing.', he: 'ממוצע נע הוא מחיר הסגירה הממוצע לאורך מספר קבוע של מפגשים קודמים, המחושב מחדש בכל יום. ממוצעים קצרים מגיבים מהר יותר; ממוצעים ארוכים מתארים את המגמה הרחבה יותר. הפעילו וכבו אותם כדי לראות מה כל אחד מהם באמת מראה.' },
    deeper: { en: 'Why 20 and 150 specifically? The 20-day average covers roughly a month of trading — short enough to track the current swing, which is why short-term traders watch for pullbacks toward it rather than breaks below it. The 150-day average gets talked about far less, but it\'s a cornerstone of professional trend-screening systems: Mark Minervini\'s well-known "Trend Template" requires price to hold above a rising 150-day average before a stock even qualifies as a long-term uptrend candidate — precisely because it reacts faster than the 200-day, catching real trend strength earlier without being as noisy as the shorter averages.', he: 'למה דווקא 20 ו-150? הממוצע ל-20 יום מכסה בערך חודש של מסחר — קצר מספיק כדי לעקוב אחרי התנודה הנוכחית, ולכן סוחרים לטווח קצר מחפשים ירידות לכיוונו במקום שבירה מתחתיו. הממוצע ל-150 יום פחות מדובר בפומבי, אבל הוא אבן יסוד במערכות סינון מגמה מקצועיות — ה"תבנית המגמה" (Trend Template) המפורסמת של מארק מינרוויני דורשת שהמחיר יחזיק מעל ממוצע 150 עולה לפני שמניה בכלל נחשבת מועמדת למגמת עלייה ארוכת טווח — בדיוק כי הוא מגיב מהר יותר מהממוצע ל-200, ותופס עוצמת מגמה אמיתית מוקדם יותר בלי להיות רועש כמו הממוצעים הקצרים יותר.' }
  },
  l4: {
    intro: { en: 'A candlestick pattern is only meaningful in context — where it sits after a trend, and what happens to price right after. The dotted box marks the candle to focus on in each chart below.', he: 'תבנית נרות משמעותית רק בהקשר — היכן היא נמצאת ביחס למגמה, ומה קורה למחיר מיד אחריה. התיבה המנוקדת מסמנת את הנר שעליו להתמקד בכל גרף למטה.' },
    deeper: { en: "One candle is a hint, not proof. A hammer or an engulfing pattern describes what happened during one or two sessions — it isn't a guarantee about tomorrow. Most experienced traders treat a single candlestick pattern as something to watch for confirmation on the next candle or two, not something to act on by itself.", he: 'נר אחד הוא רמז, לא הוכחה. פטיש או בליעה מתארים מה שקרה במהלך מפגש אחד או שניים — זו לא ערובה לגבי מחר. רוב הסוחרים המנוסים מתייחסים לתבנית נר בודדת כמשהו לחכות לאישור עליו בנר הבא או השניים הבאים, לא כמשהו לפעול לפיו בפני עצמו.' },
    extra: { en: "What to actually look for: a \"hammer\" has a small body near the top, a long lower shadow (at least twice the body's length), and little to no upper shadow — usually appearing at the end of a decline, as if price fell hard during the session and then got pushed back up by the close. \"Bullish engulfing\" is a pair of candles: a small red one, followed by a green one whose body fully covers the first candle's entire range — opening below its prior close and closing above its prior open. Flip the colours and the timing (after a rise, not a decline) and you get the bearish versions of each.", he: 'מה שבפועל מחפשים: "פטיש" הוא נר עם גוף קטן בקרבת הקצה העליון, צל תחתון ארוך (לפחות פי שניים מהגוף), וכמעט בלי צל עליון — מופיע בדרך כלל בסוף ירידה, כאילו המחיר צנח במהלך המפגש ואז נדחף חזרה למעלה עד הסגירה. "בליעה עולה" היא זוג נרות: נר אדום קטן, ואחריו נר ירוק שגופו מכסה לחלוטין את כל הטווח של הנר הראשון — פתיחה מתחת לסגירה הקודמת וסגירה מעל הפתיחה הקודמת. הפכו את הצבעים והתזמון (אחרי עלייה, לא ירידה) ותקבלו את הגרסאות הירודות של שניהם.' }
  },
  l5: {
    intro: { en: "After a strong move, price often pulls back before continuing. Fibonacci retracement marks the pullback as a percentage of that move — 23.6%, 38.2%, 50%, 61.8%, 78.6% — so traders have reference levels to watch. These levels don't predict anything by themselves; they just mark where many participants happen to be watching.", he: 'אחרי תנועה חזקה, המחיר לרוב מתקן לפני שהוא ממשיך. תיקון פיבונאצ׳י מסמן את התיקון כאחוז מאותה תנועה — 23.6%, 38.2%, 50%, 61.8%, 78.6% — כך שלסוחרים יש רמות ייחוס לעקוב אחריהן. הרמות האלה לא מנבאות שום דבר בעצמן; הן רק מסמנות איפה הרבה משתתפים בשוק צופים.' },
    deeper: { en: "Why do these specific percentages matter? Honestly, not because of anything mystical about the numbers. So many traders, algorithms, and institutions plot the exact same retracement lines that they end up placing similar buy and sell orders near the same prices — creating real supply and demand right where everyone is already looking. It's partly a self-fulfilling prophecy. One curiosity: 50% isn't actually a Fibonacci ratio at all — it was added because markets often retrace around half of a move, an older observation from Dow Theory that stuck around.", he: 'למה דווקא האחוזים האלה חשובים? בכנות, לא בגלל שום דבר מיסטי במספרים עצמם. כל כך הרבה סוחרים, אלגוריתמים ומוסדות מציירים בדיוק את אותם קווי תיקון שהם בסוף מציבים פקודות קנייה ומכירה דומות בקרבת אותם מחירים — מה שיוצר היצע וביקוש אמיתיים בדיוק במקום שכולם כבר מסתכלים עליו. זו במידה מסוימת נבואה שמגשימה את עצמה. עובדה מעניינת: 50% הוא בכלל לא יחס פיבונאצ׳י אמיתי — הוא נוסף כי שווקים לרוב מתקנים בערך חצי מתנועה, תצפית ישנה יותר מתורת דאו שנשארה.' }
  },
  l6: {
    intro: { en: 'RSI moves between 0 and 100 based on the size of recent gains versus recent losses. Above 70 is generally called "overbought," below 30 "oversold" — but neither is an automatic trade signal, as the first example below shows clearly.', he: 'RSI נע בין 0 ל-100 בהתאם לגודל הרווחים לעומת ההפסדים האחרונים. מעל 70 נקרא בדרך כלל "קניית יתר", מתחת ל-30 "מכירת יתר" — אך אף אחד מהם אינו איתות מסחר אוטומטי, כפי שהדוגמה הראשונה למטה מראה בבירור.' },
    deeper: { en: 'Two more things worth knowing: first, 50 acts as an informal dividing line — RSI consistently above 50 tends to describe an uptrend, consistently below 50 a downtrend. Second, RSI is a lagging measure, calculated from price that already happened, so by the time it flags something, part of the move is usually already behind it. Some traders shift the classic 70/30 thresholds to 80/20 during strong trends, precisely because 70/30 triggers too early and too often in a one-directional market.', he: 'עוד שני דברים ששווה לדעת: ראשית, 50 משמש כקו מפריד לא רשמי — RSI שנמצא באופן עקבי מעל 50 נוטה לתאר מגמת עלייה, ומתחת ל-50 מגמת ירידה. שנית, RSI הוא מדד מפגר, מחושב ממחיר שכבר קרה, כך שעד שהוא מציג איתות, חלק מהתנועה כבר בדרך כלל מאחוריו. חלק מהסוחרים מזיזים את הרמות הקלאסיות 70/30 ל-80/20 בזמן מגמות חזקות, בדיוק כי 70/30 מפעיל איתות מוקדם מדי ותכוף מדי בשוק חד-כיווני.' },
    extra: { en: 'One more term worth knowing: bearish divergence is when price makes a higher high, but RSI at that same moment makes a LOWER high than its own previous peak — price is still climbing, but with weakening force behind it. It is a disagreement between price and the momentum behind it, not an automatic sell signal, but an early warning that the move underneath is losing strength. (Bullish divergence is the mirror image: a lower low in price alongside a higher low in RSI.)', he: 'עוד מונח ששווה להכיר: דיוורגנס שלילי הוא מצב שבו המחיר קובע שיא גבוה יותר, אבל ה-RSI באותו רגע קובע שיא נמוך יותר מהשיא הקודם שלו — המחיר עדיין עולה, אבל בעוצמה נחלשת. זו אי-הסכמה בין המחיר למומנטום שמאחוריו, לא איתות מכירה אוטומטי, אלא אזהרה מוקדמת שהתנועה מתחת לפני השטח מאבדת כוח. (דיוורגנס חיובי הוא התמונה ההפוכה: שפל נמוך יותר במחיר לצד שפל גבוה יותר ב-RSI.)' }
  },
  l7: {
    intro: { en: 'These are recurring shapes in price action, each with a typical (not guaranteed) outcome once it completes. The dashed lines mark the structure that defines each pattern.', he: 'אלו צורות חוזרות בתנועת המחיר, לכל אחת תוצאה טיפוסית (לא מובטחת) לאחר שהיא מושלמת. הקווים המקווקווים מסמנים את המבנה שמגדיר כל תבנית.' },
    deeper: { en: 'How traders estimate a price target — a common (rough) technique is the "measured move": take the height of the pattern itself, for example the distance from the head down to the neckline in a head & shoulders, and project that same distance from the breakout point in the direction of the breakout. It\'s a starting estimate, not a promise — real moves regularly fall short of it or run well past it.', he: 'איך סוחרים מעריכים יעד מחיר — טכניקה נפוצה (וגסה) היא "התנועה הנמדדת": לוקחים את הגובה של התבנית עצמה, למשל המרחק מהראש למטה עד קו הצוואר בראש וכתפיים, ומקרינים את אותו מרחק מנקודת הפריצה בכיוון הפריצה. זו הערכת פתיחה, לא הבטחה — תנועות אמיתיות לעיתים קרובות נופלות מתחת ליעד או חורגות ממנו בהרבה.' },
    extra: { en: 'One of the common patterns: a "double bottom" is a W shape — price falls to a low, recovers, falls again to a similar (not necessarily identical) low, then breaks above the peak that sat between the two lows (the neckline). That break above the neckline is what confirms the pattern; two lows alone, without it, are still just two lows. Two highs at a similar level with a low between them is the mirror image — a "double top".', he: 'אחת מהתבניות הנפוצות: "תחתית כפולה" היא צורת W — המחיר יורד לשפל, מתאושש, יורד שוב לשפל דומה (לא בהכרח זהה), ואז פורץ מעל השיא שהיה בין שני השפלים (קו הצוואר). הפריצה מעל קו הצוואר היא מה שמאשר את התבנית; שני שפלים בלבד, בלעדיה, הם עדיין רק שני שפלים. שני שיאים בגובה דומה עם שפל ביניהם הם התמונה ההפוכה — "תקרה כפולה".' }
  }
};

export function proseFor(lessonId: string): LessonProse | null {
  return LESSON_PROSE[lessonId] ?? null;
}
