// ---------------------------------------------------------------------------
// Gaps found during QA. Each of these was a question that fell through to the
// generic fallback or matched an unrelated entry.
//
// Two provenances, both real:
//   - the first three came from screenshots of the live site — questions
//     visitors actually typed;
//   - the last four came from a coverage sweep over ~65 plainly-phrased
//     beginner questions, which is how a gap gets found BEFORE a visitor
//     hits it. What that sweep showed is that the KB was strong on named
//     concepts ("what is RSI") and weak on the questions a beginner asks
//     before they know a concept has a name ("how do I read a chart",
//     "how do I know when to sell"). Those are the entry points to the
//     whole subject, so a beginner-facing product that misses them misses
//     the people it is most for.
// ---------------------------------------------------------------------------
export const KB_QA_GAPS = [
  { id:'bull-vs-bear-market', cat:'comparisons', priority:6, sides:['bull-market','bear-market'], kw:['bull market vs bear market','difference between bull and bear market','bull and bear market','ההבדל בין שוק שורי לשוק דובי','שוק שורי לשוק דובי','שוק דובי לשורי','שוק שורי לדובי','בול מרקט ובר מרקט'],
    he:`"שוק שורי" (Bull Market) הוא תקופה ממושכת שבה מחירים עולים באופן כללי, בדרך כלל מוגדר כעלייה של 20% ומעלה משפל קודם, ומלווה באופטימיות, ביטחון של משקיעים וכלכלה מתרחבת. "שוק דובי" (Bear Market) הוא ההפך: ירידה של 20% ומעלה משיא קודם, לרוב מלווה בפסימיות, חשש ולעיתים האטה כלכלית. מקור השמות בדרך שבה החיות תוקפות: שור נועץ קרניים כלפי מעלה, ודוב מנחית טפרים כלפי מטה. חשוב לדעת: שוק דובי הוא חלק נורמלי ומחזורי מהשוק ולא אירוע חריג — היסטורית, שווקים דוביים היו קצרים יותר משווקים שוריים, ואחריהם השוק בסופו של דבר התאושש, אם כי אין ערובה לכך שזה יקרה שוב או תוך כמה זמן. ירידה קטנה יותר (כ-10%) נקראת "תיקון" (Correction) ולא שוק דובי.`,
    en:`A "bull market" is an extended period of generally rising prices, usually defined as a 20%+ rise from a prior low, accompanied by optimism, investor confidence, and an expanding economy. A "bear market" is the opposite: a 20%+ decline from a prior peak, typically accompanied by pessimism, fear, and sometimes an economic slowdown. The names come from how the animals attack: a bull thrusts its horns upward, a bear swipes its claws downward. Worth knowing: a bear market is a normal, cyclical part of markets rather than a freak event — historically, bear markets have been shorter than bull markets, and markets have eventually recovered afterward, though there's no guarantee that repeats or how long it would take. A smaller decline (around 10%) is called a "correction," not a bear market.`,
    related:['trend','pullback'] },

  { id:'what-to-do-in-a-market-drop', cat:'risk', kw:['what should i do if the market drops','market dropped 20% what do i do','should i sell when the market falls','what to do in a crash','אם השוק ירד','השוק ירד','מה כדאי לעשות','מה לעשות כשהשוק יורד','מה כדאי לי לעשות כשהשוק יורד','השוק קורס מה לעשות','מה עושים כשהשוק יורד'],
    he:`אין תשובה אחת נכונה, אבל יש כמה עקרונות שחוזרים בחומרי חינוך פיננסי: ראשית, ירידה חדה היא חלק צפוי ונורמלי מהשקעה במניות — לא סימן שמשהו "נשבר". שנית, השאלה החשובה היא לא "מה קרה השבוע" אלא האם משהו מהותי השתנה בתזה המקורית שלך או בטווח הזמן שלך. אם הכסף מיועד לעוד 15 שנה, ירידה של 20% היום היא בעיקר רעש; אם אתה צריך אותו בעוד שנה, ייתכן שהתמהיל לא התאים מלכתחילה לטווח הקצר. שלישית, מכירה בפאניקה אחרי ירידה היא הדרך להפוך הפסד "על הנייר" להפסד ממומש — וגם מקשה לחזור, כי הימים הטובים של השוק מגיעים לרוב דווקא סמוך לתקופות הגרועות. רביעית, עבור חלק מהמשקיעים ירידה היא דווקא הזדמנות להמשיך להפקיד באופן קבוע (DCA) במחירים נמוכים יותר. חשוב: זו סקירה חינוכית כללית ולא ייעוץ השקעות אישי, ואם ירידה גורמת לך מצוקה אמיתית — ייתכן שרמת הסיכון בתיק גבוהה מדי עבורך, וזו שאלה ששווה לבחון עם איש מקצוע.`,
    en:`There's no single right answer, but a few principles recur across financial-education material: first, a sharp decline is an expected, normal part of investing in stocks — not a sign something is "broken." Second, the important question isn't "what happened this week" but whether anything fundamental changed in your original thesis or your time horizon. If the money is for 15 years from now, a 20% drop today is mostly noise; if you need it in a year, the allocation may not have suited that short horizon in the first place. Third, panic-selling after a decline is how a paper loss becomes a realized one — and it also makes getting back in harder, since the market's best days often cluster right around its worst. Fourth, for some investors a decline is actually an opportunity to keep contributing regularly (DCA) at lower prices. Important: this is general educational context, not personal investment advice, and if a decline is causing you real distress, your portfolio's risk level may be too high for you — a question worth reviewing with a professional.`,
    related:['behavioral-biases','dollar-cost-averaging'] },

  { id:'how-to-evaluate-a-company', cat:'fundamentals', kw:['reasons to invest in a company','reasons not to invest in a company','pros and cons of investing in a company','how do i decide whether to invest in a company','how to evaluate a company','סיבות להשקיע בחברה','סיבות לא להשקיע','סיבות למה לא להשקיע','השקעה בחברה','איך לבדוק אם כדאי להשקיע בחברה','איך מעריכים חברה','יתרונות וחסרונות של השקעה בחברה'],
    he:`אין רשימה אוניברסלית, אבל אלה השיקולים שחוזרים שוב ושוב כשבוחנים חברה מסוימת. סימנים שנחשבים חיוביים: (1) יתרון תחרותי בר-קיימא ("מואט") שמקשה על מתחרים לחקות; (2) צמיחה עקבית בהכנסות וברווח, לא רק ברבעון בודד; (3) מאזן בריא — חוב נשלט ותזרים מזומנים חופשי חיובי; (4) תשואה גבוהה על ההון המושקע (ROIC/ROE), שמעידה שהחברה מייצרת ערך אמיתי מהכסף שלה; (5) הנהלה עם רקורד סביר בהקצאת הון. סימני אזהרה: (1) חוב גבוה במיוחד ביחס לענף, במיוחד בסביבת ריבית עולה; (2) הסתמכות על לקוח, מוצר או שוק יחיד; (3) שחיקה מתמשכת בשולי הרווח; (4) מכפיל גבוה מאוד שכבר מגלם ציפיות אופטימיות מאוד — כלומר מעט מקום לטעות; (5) דילול מתמשך של בעלי המניות (הנפקת מניות חדשות); (6) ענף בדעיכה מבנית או רגולציה מאיימת. חשוב: זו מסגרת חשיבה חינוכית כללית — היא לא מחליפה בדיקה של המספרים בפועל בדוחות החברה, ואינה ייעוץ השקעות לגבי חברה ספציפית.`,
    en:`There's no universal checklist, but these are the considerations that come up repeatedly when examining a specific company. Signs generally viewed positively: (1) a durable competitive advantage (a "moat") that makes it hard for rivals to copy; (2) consistent growth in revenue and profit, not just one strong quarter; (3) a healthy balance sheet — manageable debt and positive free cash flow; (4) a high return on invested capital (ROIC/ROE), indicating the company generates real value from its money; (5) management with a reasonable track record of capital allocation. Warning signs: (1) unusually high debt relative to its industry, especially in a rising-rate environment; (2) dependence on a single customer, product, or market; (3) persistently eroding profit margins; (4) a very high multiple that already prices in very optimistic expectations — meaning little room for error; (5) ongoing shareholder dilution (issuing new shares); (6) a structurally declining industry or looming regulation. Important: this is a general educational framework — it doesn't replace examining the actual numbers in the company's filings, and it isn't investment advice about any specific company.`,
    related:['fundamental','moat'] },

  { id:'ticker-symbol', cat:'basics', priority:2, kw:['ticker','ticker symbol','stock symbol','what is a ticker','what does the symbol mean','סימול','מה זה סימול','סימבול','סמל מניה','הסימול של המניה','איך קוראים לסימול'],
    he:`סימול (Ticker) הוא הקיצור הייחודי שמזהה נייר ערך בבורסה מסוימת — AAPL לאפל, MSFT למיקרוסופט, NVDA לאנבידיה. הוא קיים כי שמות חברות אינם ייחודיים ואינם יציבים: שתי חברות יכולות להיקרא דומה, חברה יכולה לשנות שם, ומערכת מסחר צריכה מזהה קצר וחד-משמעי שלא משתנה בכל פעם שמישהו מנסח את השם אחרת. שלוש נקודות שמבלבלות מתחילים: (1) הסימול שייך לבורסה, לא לחברה — אותה חברה יכולה להיסחר תחת סימולים שונים בבורסות שונות, ולכן מציינים לפעמים גם את הבורסה (NASDAQ:AAPL); (2) סימול שמתפנה יכול לעבור לחברה אחרת לגמרי אחרי מחיקה מהמסחר, כך שסימול היסטורי לא תמיד מצביע על מי שאתה חושב; (3) בבורסה בתל אביב נהוג מספר נייר בן חמש-שש ספרות לצד השם, ולא סימול אותיות כמו בארה"ב. כשמחפשים מניה כאן באתר, הסימול הוא הדרך הבטוחה ביותר להגיע בדיוק לחברה שהתכוונת אליה.`,
    en:`A ticker symbol is the unique shorthand that identifies a security on a particular exchange — AAPL for Apple, MSFT for Microsoft, NVDA for Nvidia. It exists because company names are neither unique nor stable: two companies can be named similarly, a company can rebrand, and a trading system needs a short, unambiguous identifier that doesn't change every time someone phrases the name differently. Three things that trip up beginners: (1) the symbol belongs to the exchange, not the company — the same company can trade under different symbols on different exchanges, which is why you sometimes see the exchange named too (NASDAQ:AAPL); (2) a symbol that is freed up can later be reassigned to an entirely different company after a delisting, so a historical ticker doesn't always point at who you think; (3) the Tel Aviv exchange conventionally uses a five- or six-digit security number alongside the name rather than a letter ticker as in the US. When searching for a stock on this site, the symbol is the most reliable way to land on exactly the company you meant.`,
    related:['exchange','stock'] },

  { id:'how-to-read-a-chart', cat:'technical', priority:3, kw:['how do i read a chart','how to read a chart','how do you read a stock chart','read a stock chart','reading a chart','reading charts','i dont understand the chart','i can not read the chart','what am i looking at on a chart','איך קוראים גרף','איך קוראים גרף מניה','איך לקרוא גרף','לקרוא גרף','איך מבינים גרף','איך קוראים את הגרף','אני לא מבין את הגרף','לא מבין את הגרף','לא מבינה את הגרף','מה רואים בגרף','איך מסתכלים על גרף'],
    he:`גרף מניה נקרא בשכבות, וכמעט כל הבלבול של מתחילים נובע מניסיון לקרוא את כולן בבת אחת. השכבה הראשונה היא הצירים: הציר האופקי הוא זמן, הציר האנכי הוא מחיר — ולפני כל דבר אחר כדאי לבדוק איזה טווח זמן מוצג, כי אותה מניה בדיוק נראית כמו קריסה בגרף של חודש וכמו עלייה יציבה בגרף של חמש שנים. השכבה השנייה היא הגוף: כל נר מייצג תקופה אחת (יום, שעה) ומספר ארבעה מספרים — פתיחה, סגירה, הגבוה והנמוך; גוף ארוך אומר שהמחיר זז הרבה מהפתיחה לסגירה, וצל ארוך אומר שהמחיר הגיע לאנשהו ונדחה משם. השכבה השלישית היא הנפח, העמודות שמתחת לגרף: הן לא מחיר אלא כמה מניות עברו יד, וזה מה שמבדיל תנועה שיש מאחוריה עניין אמיתי מתנועה דלילה. השכבה הרביעית היא מה שאתה מצייר בעצמך — קווי תמיכה והתנגדות, מגמה, ממוצעים נעים. סדר קריאה מעשי: קודם קבע את טווח הזמן, אחר כך את כיוון המגמה הכללי, אחר כך חפש אזורים שהמחיר חזר אליהם יותר מפעם אחת, ורק בסוף הסתכל על נרות בודדים. ההפך — להתחיל מנר אחד — הוא בדיוק איך שמפרשים רעש כאילו הוא אות. באתר הזה השיעורים בונים את השכבות האלה אחת-אחת, ואפשר להתחיל מהשיעור על נרות ולהמשיך לתמיכה והתנגדות.`,
    en:`A stock chart is read in layers, and nearly all beginner confusion comes from trying to read them all at once. The first layer is the axes: horizontal is time, vertical is price — and before anything else, check which time range is displayed, because the exact same stock looks like a collapse on a one-month chart and like a steady climb on a five-year one. The second layer is the body: each candle represents one period (a day, an hour) and tells you four numbers — open, close, high and low; a long body means price travelled a long way from open to close, and a long wick means price reached somewhere and got pushed back from it. The third layer is volume, the bars beneath the chart: those aren't price, they're how many shares changed hands, and that's what separates a move with real interest behind it from a thin one. The fourth layer is what you draw yourself — support and resistance lines, trend, moving averages. A practical reading order: first fix the time range, then the overall trend direction, then look for areas price has returned to more than once, and only then look at individual candles. Doing it backwards — starting from one candle — is precisely how noise gets read as signal. The lessons on this site build these layers one at a time; the candlestick lesson is a good place to start, followed by support and resistance.`,
    related:['candlestick','support-resistance'] },

  { id:'when-to-sell', cat:'risk', priority:2, kw:['when to sell','when should i sell','how do i know when to sell','how do you know when to sell a stock','when do i sell','knowing when to sell','מתי למכור','מתי כדאי למכור','איך יודעים מתי למכור','איך יודעים מתי למכור מניה','מתי מוכרים','מתי מוכרים מניה','מתי לצאת מהפוזיציה','מתי לצאת ממניה'],
    he:`אין סימן שאומר "עכשיו". מה שיש הוא ההבחנה בין שתי שאלות שונות שנשמעות זהות: "האם המחיר ירד?" ו"האם משהו השתנה?". ירידה במחיר לבדה אינה סיבה — היא רק אומרת שהשוק מתמחר אחרת, ואם התזה המקורית שלך עדיין תקפה, מכירה בגללה היא בדיוק ההתנהגות שהופכת ירידה זמנית להפסד ממומש. הסיבות שכן חוזרות בחומרי חינוך פיננסי כעילה לבחון מכירה הן אחרות: התזה שקנית לפיה נשברה (המוצר, השוק או היתרון התחרותי השתנו מהותית ולא רק המחיר); הפוזיציה תפחה עד שהיא מהווה חלק לא סביר מהתיק והסיכון כבר לא מפוזר כפי שהתכוונת; מצאת שימוש טוב יותר לכסף; או — הסיבה הפשוטה והנפוצה ביותר — אתה צריך את הכסף, כי טווח הזמן שבגללו קנית הגיע לסופו. הכלי שנועד להוציא את ההחלטה מרגע הלחץ הוא לקבוע את הכללים מראש: מה יגרום לי למכור, ובאיזה מחיר או באיזה תנאי — כשהמצב עדיין תיאורטי ולא כשהמסך אדום. באתר יש על זה שני מושגים ייעודיים, סטופ לוס ו-Take Profit, ושווה לקרוא עליהם יחד ולא בנפרד. חשוב: זו מסגרת חשיבה חינוכית כללית ולא ייעוץ מתי למכור נייר מסוים — ההחלטה תלויה בנתונים שלך, שאין לי גישה אליהם.`,
    en:`There is no signal that says "now." What there is, is the distinction between two questions that sound identical: "has the price fallen?" and "has something changed?" A falling price on its own isn't a reason — it only says the market is pricing things differently, and if your original thesis still holds, selling because of it is precisely the behaviour that turns a temporary decline into a realized loss. The reasons that do recur across financial-education material as grounds for reviewing a sale are different ones: the thesis you bought on has broken (the product, the market or the competitive advantage changed materially, not just the price); the position has grown until it's an unreasonable share of the portfolio and the risk is no longer spread the way you intended; you've found a better use for the money; or — the simplest and most common reason — you need the money, because the time horizon you bought for has arrived. The tool for getting the decision out of the stressful moment is to set the rules in advance: what would make me sell, and at what price or under what condition — decided while it's still theoretical, not while the screen is red. This site covers two dedicated concepts for that, stop loss and take profit, and they're worth reading together rather than separately. Important: this is a general educational framework, not advice on when to sell any particular holding — that depends on your own circumstances, which I have no access to.`,
    related:['stop-loss','take-profit-vs-stop-loss'] },

  { id:'why-am-i-losing-money', cat:'behavioral', priority:2, kw:['why am i losing money','why do i keep losing money','why am i down','i keep losing money','why do i always lose','למה אני מפסיד כסף','למה אני מפסיד','למה אני מפסידה','אני מפסיד כסף','למה אני תמיד מפסיד','למה הפסדתי כסף','למה התיק שלי באדום'],
    he:`אין לי גישה לתיק שלך, אז אני לא יכול להגיד לך למה דווקא אתה מפסיד — אבל אני כן יכול לפרט את הסיבות שחוזרות שוב ושוב בספרות, כדי שתוכל לבדוק בעצמך איזו מהן רלוונטית. ראשית, ההבחנה החשובה ביותר: הפסד "על הנייר" והפסד ממומש אינם אותו דבר. תיק שאדום השבוע והתוכנית שלו היא לעשר שנים לא הפסיד כלום עדיין — הוא רק נמדד ברגע גרוע. שנית, אופק זמן לא תואם: כסף שנכנס למניות ונדרש בחזרה בתוך שנה-שנתיים נמדד בדיוק בחלון שבו תנודתיות היא הכי גדולה ביחס לתשואה הצפויה. שלישית, עלויות ומסחר יתר: כל קנייה ומכירה גובה עמלה ומרווח, ומחקרים על משקיעים פרטיים מראים באופן עקבי שהפעילים ביותר נוטים לתוצאות גרועות יותר מהפסיביים — לא בגלל בחירת מניות גרועה יותר, אלא בגלל תדירות. רביעית, גודל פוזיציה: אחזקה אחת גדולה מדי הופכת כל טעות בודדת לתוצאה של כל התיק. חמישית, רדיפה — קנייה אחרי עלייה חדה ומכירה אחרי ירידה חדה היא הדפוס ההתנהגותי המתועד ביותר, והוא בדיוק "קנה גבוה, מכור נמוך" בהילוך איטי. שישית, השוואה לנקודת ייחוס שרירותית: המחיר שבו קנית הוא מספר שמשמעותי רק לך, ולא לשוק. שווה לקרוא כאן על הטיות התנהגותיות ועל פיזור סיכונים. וחשוב מכל: אם ההפסד גורם לך מצוקה אמיתית או שהכסף הזה נחוץ לך בקרוב, רמת הסיכון כנראה לא מתאימה לך, וזו שאלה לאיש מקצוע ולא לצ'אט.`,
    en:`I have no access to your portfolio, so I can't tell you why you specifically are losing — but I can lay out the reasons that recur in the literature, so you can check which one applies. First, the most important distinction: a paper loss and a realized loss are not the same thing. A portfolio that's red this week on a ten-year plan hasn't lost anything yet — it's just being measured at a bad moment. Second, a mismatched time horizon: money put into stocks and needed back within a year or two is being measured in exactly the window where volatility is largest relative to expected return. Third, costs and overtrading: every buy and sell pays a commission and a spread, and studies of retail investors consistently find that the most active ones do worse than the passive ones — not because they pick worse stocks, but because of frequency. Fourth, position size: one holding that's too large turns any single mistake into the whole portfolio's result. Fifth, chasing — buying after a sharp rise and selling after a sharp fall is the single best-documented behavioural pattern, and it is "buy high, sell low" in slow motion. Sixth, anchoring to an arbitrary reference point: the price you paid is a number that matters only to you, not to the market. The entries here on behavioural biases and diversification are worth reading. And most importantly: if the loss is causing you real distress, or you need that money soon, the risk level probably doesn't suit you — and that's a question for a professional, not a chat assistant.`,
    related:['behavioral-biases','diversification'] },
];


export const entries = KB_QA_GAPS;
