  { id:'capital-market', cat:'basics', kw:['what is the stock market','what is the capital market','capital markets','financial markets','שוק ההון','מה זה שוק ההון','מהו שוק ההון'],
    he:`שוק ההון הוא המקום (היום בעיקר דיגיטלי) שבו חברות וממשלות מגייסות כסף מהציבור, ומשקיעים קונים ומוכרים נכסים פיננסיים כמו מניות ואג"ח. תפקידו הכלכלי המרכזי הוא לחבר בין מי שיש לו כסף עודף ורוצה להשקיע, לבין מי שצריך כסף כדי לצמוח — כשבתמורה המשקיע מקבל סיכוי לתשואה (וגם סיכון להפסד).`,
    en:`The capital market is where companies and governments raise money from the public, and investors buy and sell financial assets like stocks and bonds. Its core economic role is connecting people who have spare money and want to invest with entities that need money to grow — in exchange, the investor gets a chance at a return (and also the risk of a loss).`,
    related:['stock','bond'] },

  { id:'stock', cat:'basics', kw:['stock','share','shares','equity','מניה','מניות','מהי מניה','נייר ערך','ניירות ערך','security'],
    he:`מניה היא פיסת בעלות בחברה. כשקונים מניה, בפועל קונים חלק קטן מהחברה — אם החברה מרוויחה וגדלה, שווי המניה נוטה לעלות; אם היא נכשלת, השווי יכול לרדת. חלק מהחברות גם מחלקות חלק מהרווח למחזיקי המניות (דיבידנד). "נייר ערך" הוא המונח הרחב יותר שכולל גם מניות וגם אג"ח וגם מכשירים פיננסיים אחרים שניתן לסחור בהם.`,
    en:`A stock is a piece of ownership in a company. When you buy a share, you're literally buying a small slice of that company — if it earns money and grows, the share tends to become more valuable; if it struggles, the value can fall. Some companies also pass part of their profit directly to shareholders as a dividend. "Security" is the broader term that covers stocks, bonds, and other tradable financial instruments.`,
    related:['capital-market','how-trading-works'] },

  { id:'bond', cat:'basics', kw:['bond','bonds','אג"ח','אגרת חוב','אגרות חוב'],
    he:`אג"ח (אגרת חוב) היא בעצם הלוואה: הרוכש מלווה כסף לממשלה או לחברה שהנפיקה אותה, ומקבל בתמורה ריבית קבועה (או משתנה) לאורך זמן, ובסוף התקופה מקבל בחזרה את הקרן. בגדול, אג"ח נחשבות פחות מסוכנות ממניות — אבל גם פוטנציאל התשואה שלהן נמוך יותר בממוצע. חשוב לזכור: מחיר אג"ח בשוק המשני זז הפוך לריבית — כשריבית עולה, מחיר אג"ח קיימות בדרך כלל יורד.`,
    en:`A bond is essentially a loan: the buyer lends money to a government or company that issued it, receiving fixed (or variable) interest over time, and gets the principal back at the end of the term. Broadly, bonds are considered less risky than stocks — but their average return potential is lower too. One key point: a bond's market price moves inversely to interest rates — when rates rise, the price of existing bonds usually falls.`,
    related:['bond-price-interest-rate','interest-rate'] },

  { id:'etf', cat:'basics', kw:['etf','exchange traded fund','קרן סל','תעודת סל'],
    he:`ETF (קרן סל) היא קרן שנסחרת בבורסה בדיוק כמו מניה, אבל מחזיקה בתוכה סל שלם של נכסים — למשל את כל מניות מדד ה-S&P 500 בבת אחת. קניית ETF אחד נותנת פיזור מיידי בלי לקנות כל מניה בנפרד, ולרוב בעמלות ניהול נמוכות יחסית לקרנות מנוהלות באופן אקטיבי.`,
    en:`An ETF (exchange-traded fund) is a fund that trades on the stock exchange just like a share, but holds a whole basket of assets inside it — for example every stock in the S&P 500 at once. Buying one ETF gives instant diversification without buying each stock separately, usually with relatively low fees compared to actively managed funds.`,
    facets:{
      pros:{ he:`היתרונות של ETF: פיזור מיידי על פני עשרות או מאות חברות בקנייה אחת, מה שמקטין את הסיכון הספציפי לחברה בודדת; דמי ניהול נמוכים משמעותית מקרן מנוהלת אקטיבית; נזילות — נסחר לאורך כל יום המסחר כמו מניה רגילה; ושקיפות, כי בדרך כלל אפשר לראות בדיוק מה מוחזק בקרן.`,
             en:`Advantages of an ETF: instant diversification across dozens or hundreds of companies in a single purchase, which reduces exposure to any one company; management fees significantly lower than an actively managed fund; liquidity — it trades throughout the session like an ordinary stock; and transparency, since you can usually see exactly what the fund holds.` },
      cons:{ he:`החסרונות של ETF: אתה מקבל את ממוצע השוק ולא תשואה חריגה — הפיזור מקטין גם את הסיכוי לרווח גדול; בקרן רחבה אתה קונה גם חברות שלא היית בוחר בעצמך; קרנות סקטוריאליות או ממונפות יכולות להיות מסוכנות בהרבה ממה שנדמה; יש עדיין דמי ניהול שנגרעים לאורך שנים; ובקרנות קטנות ולא נזילות המרווח (Spread) עלול להיות רחב ולייקר את הקנייה והמכירה.`,
             en:`Drawbacks of an ETF: you get the market average rather than outsized returns — diversification also caps the upside; in a broad fund you're buying companies you wouldn't have picked yourself; sector or leveraged ETFs can be far riskier than they appear; there are still management fees eroding returns over years; and in small, illiquid funds the bid-ask spread can be wide, making buying and selling more expensive.` }
    },
    related:['index','diversification'] },

  { id:'index', cat:'basics', kw:['index','indices','stock index','s&p 500','s&p500','nasdaq','nasdaq composite','nasdaq 100','dow jones','tel aviv 35','ta-125','מדד','מדדים','מדד המניות','נאסד"ק','דאו ג\'ונס','וול סטריט','wall street'],
    he:`מדד מניות הוא "סל" שמייצג קבוצת מניות יחד, כדי לתת תמונה כללית על שוק שלם או ענף במקום לעקוב אחרי כל מניה בנפרד. S&P 500 עוקב אחרי כ-500 מהחברות הגדולות בארה"ב על פני כל הענפים, בעוד ה-Nasdaq (שהוא גם שם של הבורסה עצמה וגם שם למשפחת מדדים כמו Nasdaq Composite ו-Nasdaq 100) נוטה להיות מוטה יותר לכיוון חברות טכנולוגיה. "וול סטריט" הוא כינוי עממי (על שם הרחוב בניו יורק) לשוק ההון האמריקאי בכללותו, לא בורסה ספציפית. כשמדד עולה, זה סימן שרוב המניות שבתוכו עלו בממוצע — לא בהכרח כולן.`,
    en:`A stock index is a "basket" that represents a group of stocks together, giving a general picture of a whole market or sector instead of tracking every stock individually. The S&P 500 tracks roughly 500 of the largest US companies across every industry, while "Nasdaq" is both the name of the exchange itself and a family of indices (Nasdaq Composite, Nasdaq 100) that tends to be more heavily weighted toward technology companies. "Wall Street" is an informal nickname (after the street in New York) for the US capital market as a whole, not a specific exchange. When an index rises, it means most of the stocks inside it rose on average — not necessarily every single one.`,
    related:['etf','sp500-vs-nasdaq100'] },

  { id:'exchange', cat:'basics', kw:['stock exchange','exchange','בורסה','מהי בורסה','בורסה לניירות ערך'],
    he:`בורסה היא שוק מאורגן ומפוקח שבו קונים ומוכרים נפגשים (היום כמעט תמיד באופן אלקטרוני) כדי לסחור במניות ובניירות ערך אחרים לפי כללים ברורים. חברה שרוצה שמניותיה ייסחרו בבורסה צריכה לעמוד בדרישות רישום ודיווח מסוימות, וזה חלק ממה שנותן למשקיעים ביטחון בסיסי לגבי שקיפות המידע.`,
    en:`A stock exchange is an organized, regulated marketplace where buyers and sellers meet (today almost always electronically) to trade shares and other securities under clear rules. A company that wants its shares to trade on an exchange has to meet certain listing and disclosure requirements, which is part of what gives investors basic confidence in the transparency of the information available.`,
    related:['index','ipo'] },

  { id:'broker', cat:'basics', kw:['broker','brokerage','ברוקר','בית השקעות','ברוקראז'],
    he:`ברוקר (בית השקעות/מתווך) הוא הגורם שדרכו משקיע פרטי בפועל שולח פקודות קנייה ומכירה לבורסה — אי אפשר לסחור בבורסה ישירות בלי מתווך מורשה. ברוקרים שונים נבדלים בעמלות מסחר, בטווח השווקים שאפשר לגשת אליהם דרכם, ובכלים שהם מציעים למשתמש.`,
    en:`A broker (brokerage) is the entity through which a private investor actually sends buy and sell orders to the exchange — you can't trade directly on an exchange without a licensed intermediary. Different brokers vary in trading fees, which markets you can access through them, and the tools they offer users.`,
    related:['how-trading-works','order-types'] },

  { id:'portfolio', cat:'basics', kw:['portfolio','investment portfolio','תיק השקעות','תיק','פורטפוליו'],
    he:`תיק השקעות הוא אוסף כל הנכסים הפיננסיים שמשקיע מחזיק ביחד — מניות, אג"ח, קרנות ואולי נכסים נוספים. מסתכלים על תיק ההשקעות כמכלול (לא רק על כל נכס בנפרד) כדי להבין את רמת הסיכון הכוללת, הפיזור, וההתאמה למטרות ולטווח הזמן של המשקיע.`,
    en:`An investment portfolio is the whole collection of financial assets an investor holds together — stocks, bonds, funds, and maybe other assets. You look at the portfolio as a whole (not just each holding separately) to understand overall risk level, diversification, and fit with the investor's goals and time horizon.`,
    related:['diversification','asset-allocation'] },

  { id:'order-types', cat:'basics', kw:['market order','limit order','order types','types of orders','פקודת market','פקודת limit','פקודת שוק','פקודה מוגבלת','סוגי פקודות'],
    he:`פקודת Market (שוק) אומרת "קנה/מכור מיד, במחיר הטוב הזמין כרגע" — מבטיחה ביצוע מהיר אבל לא מבטיחה מחיר מדויק. פקודת Limit קובעת מחיר מקסימלי (לקנייה) או מינימלי (למכירה) שבו מוכנים לבצע — מבטיחה מחיר, אבל לא מבטיחה שהעסקה בכלל תתבצע. פקודת Stop Loss (סטופ לוס) היא הוראה אוטומטית למכור אם המחיר יורד לרמה מסוימת, כדי להגביל הפסד מראש בלי לשבת ולעקוב כל הזמן. פקודת Take Profit (טייק פרופיט) היא ההפך — הוראה אוטומטית למכור (או לסגור פוזיציית Short) אם המחיר מגיע ליעד רווח מסוים שקבעת מראש, כדי לנעול רווח בלי צורך לעקוב ולהחליט בזמן אמת. שילוב נפוץ בקרב סוחרים: לקבוע Stop Loss ו-Take Profit יחד בכניסה לעסקה, כדי שיחס הסיכוי-סיכון יהיה ברור מראש.`,
    en:`A market order says "buy/sell right now, at the best price currently available" — it guarantees fast execution but not an exact price. A limit order sets a maximum price (to buy) or minimum price (to sell) you're willing to accept — it guarantees the price, but not that the trade will happen at all. A stop-loss order automatically sells if the price drops to a certain level, capping a potential loss in advance without needing to watch the position constantly. A take-profit order is the opposite — an automatic order to sell (or close a short position) once the price reaches a profit target you set in advance, locking in a gain without needing to watch and decide in real time. A common combination among traders: setting both a stop-loss and a take-profit together right when entering a trade, so the risk/reward ratio is clear from the start.`,
    related:['broker','risk-reward-ratio'] },

  { id:'how-trading-works', cat:'basics', kw:['what happens when i buy a stock','who sells me the stock','who sells it to me','who is selling me the stock','change hands','changing hands','stock changes hands','shares traded hands','מה קורה כשקונים מניה','מי מוכר לי את המניה','מי מוכר לי','ממי אני קונה','החלפת ידיים','עברה ידיים','עברה מיד ליד','מניה עברה יד'],
    he:`כשאתה קונה מניה, אתה לא קונה אותה "מהחברה" עצמה (חוץ מבמקרה נדיר של הנפקה) אלא ממשקיע אחר שכבר החזיק בה והחליט למכור — הבורסה והברוקר רק מתווכים ומחברים בין הצדדים. הביטוי "המניה החליפה ידיים" פשוט מתאר עסקה כזו: מוכר אחד ויתר על הבעלות, וקונה אחר קיבל אותה, בדיוק במחיר שבו שני הצדדים הסכימו. לכן מחיר מניה תמיד קובע נקודת שיווי משקל רגעית בין מי שמוכן למכור לבין מי שמוכן לקנות.`,
    en:`When you buy a share, you're not buying it "from the company" itself (except in the rare case of a new offering) — you're buying it from another investor who already held it and decided to sell; the exchange and broker just match and connect the two sides. The phrase "the stock changed hands" simply describes that trade: one seller gave up ownership and a buyer received it, at whatever price both sides agreed on. That's why a stock's price always reflects a momentary equilibrium point between whoever is willing to sell and whoever is willing to buy.`,
    related:['why-price-moves','bid-ask-spread'] },

  { id:'why-price-moves', cat:'basics', kw:['why does a stock price go up','why does a stock price go down','why stock prices move','why does price change','למה מחיר מניה עולה','למה מחיר מניה יורד','למה המניה עולה','למה המניה יורדת'],
    he:`מחיר מניה נקבע ברגע נתון על ידי המפגש בין מה שקונים מוכנים לשלם לבין מה שמוכרים מוכנים לקבל. מחיר עולה כשיש יותר ביקוש אגרסיבי (קונים מוכנים לשלם יותר כדי לזכות בעסקה) ביחס להיצע, ויורד כשההפך נכון. הגורמים שמניעים את הביקוש וההיצע האלה יכולים להיות כל דבר: דוחות כספיים, ציפיות עתידיות, מצב הריבית והכלכלה, חדשות ספציפיות לחברה, ואפילו סנטימנט כללי בשוק.`,
    en:`A stock's price at any moment is set by the meeting point between what buyers are willing to pay and what sellers are willing to accept. Price rises when there's more aggressive demand (buyers willing to pay more to win the trade) relative to supply, and falls when the opposite is true. What drives that demand and supply can be almost anything: earnings reports, future expectations, interest rates and the economy, company-specific news, and even general market sentiment.`,
    related:['how-trading-works','bid-ask-spread'] },

  { id:'bid-ask-spread', cat:'basics', kw:['bid','ask','bid ask','spread','bid ask spread','ביד','אסק','מרווח','spread מסחר'],
    he:`Bid הוא המחיר הגבוה ביותר שמישהו מוכן כרגע לשלם כדי לקנות, ו-Ask (או Offer) הוא המחיר הנמוך ביותר שמישהו מוכן כרגע לקבל כדי למכור. Spread הוא הפער בין השניים. Spread צר מעיד בדרך כלל על מניה נזילה מאוד עם הרבה מסחר; Spread רחב מעיד על נזילות נמוכה יותר, ומשמעותו בפועל היא עלות מסחר נוספת (אתה קונה ב-Ask הגבוה יותר ומוכר ב-Bid הנמוך יותר).`,
    en:`The bid is the highest price someone is currently willing to pay to buy, and the ask (or offer) is the lowest price someone is currently willing to accept to sell. The spread is the gap between the two. A tight spread usually signals a very liquid, heavily traded stock; a wide spread signals lower liquidity, and in practice acts as an extra trading cost (you buy at the higher ask and sell at the lower bid).`,
    related:['liquidity','how-trading-works'] },

  { id:'liquidity', cat:'basics', kw:['liquidity','liquid stock','illiquid','נזילות','נכס נזיל','ליקווידיטי'],
    he:`נזילות מתארת כמה קל לקנות או למכור נכס במהירות בלי להשפיע משמעותית על המחיר שלו. מניה עם נפח מסחר גבוה ו-Spread צר נחשבת נזילה מאוד; מניה עם מעט קונים ומוכרים נחשבת פחות נזילה — ואז אפילו הזמנה קטנה יחסית יכולה להזיז את המחיר בצורה משמעותית.`,
    en:`Liquidity describes how easily an asset can be bought or sold quickly without significantly moving its price. A stock with high trading volume and a tight spread is considered very liquid; a stock with few buyers and sellers is considered less liquid — and then even a relatively small order can move the price meaningfully.`,
    related:['bid-ask-spread','why-price-drops-with-buyers'] },

  { id:'why-price-drops-with-buyers', cat:'basics', kw:['many buyers but price drops','lots of buying volume but price falls','הרבה קונים אבל המניה יורדת','למה יש ביקוש והמניה יורדת'],
    he:`תופעה שמבלבלת הרבה מתחילים: אפשר לראות "הרבה קונים" (נפח מסחר גבוה) והמחיר בכל זאת יורד. הסיבה: נפח מסחר גבוה אומר שהרבה מניות החליפו ידיים — אבל זה לא אומר שהקונים "ניצחו". אם המוכרים היו אגרסיביים יותר (מוכנים למכור במחירים נמוכים והולכים כדי לצאת), המחיר ירד למרות שגם קונים רבים השתתפו בעסקאות. במילים אחרות: נפח מודד פעילות, לא כיוון.`,
    en:`A common source of confusion for beginners: you can see "lots of buyers" (high trading volume) and the price still falls. The reason: high volume means many shares changed hands — but it doesn't mean buyers "won". If sellers were more aggressive (willing to sell at progressively lower prices to get out), the price falls even though plenty of buyers were also active in those trades. In other words: volume measures activity, not direction.`,
    related:['liquidity','volume'] },

  { id:'short-selling', cat:'basics', kw:['short','short selling','shorting a stock','go short','if i short a stock','long position','long a stock','is shorting the same as selling','long vs short','שורט','מכירה בחסר','לונג','פוזיציית לונג','פוזיציה ארוכה','האם שורט זה כמו למכור מניה שיש לי','למכור מניה שיש לי'],
    he:`Short (מכירה בחסר) הוא הימור על ירידת מחיר: הסוחר "שואל" מניות (בדרך כלל דרך הברוקר), מוכר אותן מיד, ומקווה לקנות אותן בחזרה במחיר נמוך יותר בעתיד כדי להחזיר אותן — הרווח הוא ההפרש. הסיכון ב-Short תיאורטית בלתי מוגבל, כי מחיר מניה יכול לעלות בלי הגבלה עליונה ברורה, בניגוד לקנייה רגילה ("פוזיציית Long" — פשוט להחזיק את הנכס ולצפות שיעלה), שבה ההפסד המקסימלי הוא הסכום שהושקע. חשוב להבחין: מכירה של מניה שכבר יש לך (לסגור פוזיציית Long קיימת) היא לא Short — זו פשוט מימוש רווח או הפסד על נכס שכבר בבעלותך. Short הוא הפוך: פותחים פוזיציה חדשה על ידי מכירת מניה שאין לך בכלל (שאולה), מתוך ציפייה לקנות אותה בזול יותר בעתיד.`,
    en:`Short selling is a bet that price will fall: the trader "borrows" shares (usually via the broker), sells them immediately, and hopes to buy them back later at a lower price to return them — the profit is the difference. The risk in a short position is theoretically unlimited, because a stock's price can rise without a clear upper limit, unlike a regular "long" position (simply holding the asset expecting it to rise), where the maximum loss is the amount invested. Important distinction: selling a stock you already own (to close an existing long position) is NOT shorting — that's simply realizing a gain or loss on an asset you already hold. Shorting is the opposite: opening a new position by selling a stock you don't own at all (borrowed), expecting to buy it back cheaper later.`,
    related:['margin','short-squeeze'] },

  { id:'hedging', cat:'basics', kw:['hedge','hedging','hedge risk','הדג\'','הדג','גידור','גידור סיכונים'],
    he:`גידור (Hedging) הוא נקיטת עמדה נוספת שמטרתה לקזז סיכון קיים בתיק, גם אם היא מקטינה רווח פוטנציאלי. דוגמה: משקיע שמחזיק הרבה מניות טכנולוגיה עשוי לקנות אופציית Put על מדד הנאסד"ק — אם השוק יורד, ההפסד במניות מתקזז חלקית ברווח מהאופציה. חברות עושות זאת גם ברמת העסק: יצואנית עשויה לגדר את שער החליפין כדי לא להיפגע מתנודות מטבע. המחיר של גידור הוא בדרך כלל עלות ישירה (פרמיית האופציה, למשל) או ויתור על חלק מהרווח הפוטנציאלי.`,
    en:`Hedging is taking an additional position specifically to offset an existing risk in a portfolio, even if it reduces potential profit. Example: an investor heavily invested in tech stocks might buy a put option on the Nasdaq index — if the market falls, the loss in the stocks is partly offset by a gain on the option. Companies hedge too: an exporter might hedge currency exchange rates to avoid being hurt by currency swings. The cost of hedging is usually a direct expense (the option's premium, for example) or giving up some potential upside.`,
    related:['options-basics','risk'] },

  { id:'margin', cat:'basics', kw:['margin','margin trading','margin account','מרג\'ין','מסחר במינוף','חשבון מרג\'ין'],
    he:`מסחר במרג'ין פירושו לווה כסף מהברוקר כדי לקנות (או לפתוח פוזיציית Short) בסכום גדול יותר ממה שיש לך בפועל. זה מגדיל גם רווח פוטנציאלי וגם הפסד פוטנציאלי (מינוף), ובמקרה של הפסד גדול מדי הברוקר יכול להוציא "קול מרג'ין" (Margin Call) שדורש להפקיד עוד כסף מיד או שהפוזיציה תיסגר בכפייה.`,
    en:`Margin trading means borrowing money from the broker to buy (or open a short position) with a larger amount than you actually have. This amplifies both potential gain and potential loss (leverage), and if the loss gets too large the broker can issue a "margin call" requiring you to deposit more money immediately or the position gets closed by force.`,
    related:['short-selling','leverage'] },

  { id:'premarket-afterhours', cat:'basics', kw:['pre market','premarket','after hours','after-hours trading','טרום מסחר','אחרי שעות המסחר'],
    he:`מסחר טרום-פתיחה (Pre-market) ואחרי-הנעילה (After-hours) הם חלונות מסחר מחוץ לשעות הרשמיות של הבורסה, עם פחות משתתפים ופחות נזילות. תגובות חדות לחדשות (למשל דוחות רבעוניים שמתפרסמים אחרי הנעילה) קורות לרוב שם קודם, לפני שהמחיר "מתייצב" יותר במסחר הרגיל למחרת.`,
    en:`Pre-market and after-hours trading are trading windows outside the exchange's official hours, with fewer participants and lower liquidity. Sharp reactions to news (for example quarterly earnings released after the close) often happen there first, before the price tends to settle more during regular trading the next day.`,
    related:['liquidity','earnings-season'] },

  { id:'gap', cat:'basics', kw:['gap','price gap','gap up','gap down','גאפ','פער מחיר'],
    he:`Gap הוא קפיצה במחיר בין הסגירה של יום מסחר אחד לפתיחה של היום הבא, בלי מסחר ברצף שביניהם — בדרך כלל בעקבות חדשות שהתפרסמו בזמן שהבורסה הייתה סגורה. Gap כלפי מעלה משאיר "חלל" ריק בגרף מתחת למחיר החדש, ולהפך ב-Gap כלפי מטה; לעיתים המחיר חוזר וממלא את החלל הזה מאוחר יותר ("סוגר את הגאפ"), אבל זה לא כלל בטוח.`,
    en:`A gap is a jump in price between one trading day's close and the next day's open, with no trading in between — usually following news released while the exchange was closed. A gap up leaves an empty "hole" on the chart below the new price, and a gap down does the opposite; sometimes price later returns to fill that hole ("closing the gap"), but that's not a guaranteed rule.`,
    related:['premarket-afterhours','volatility'] },

  { id:'market-cap', cat:'basics', kw:['market cap','market capitalization','שווי שוק'],
    he:`שווי שוק (Market Cap) הוא מחיר מניה אחת כפול מספר המניות הקיימות — כלומר, כמה שווה כל החברה לפי מחיר המסחר הנוכחי. הוא משמש לחלוקת חברות לגדלים: חברות "ענק" (Mega/Large cap), חברות בינוניות (Mid cap) וחברות קטנות (Small cap), כאשר חברות קטנות בדרך כלל תנודתיות יותר.`,
    en:`Market capitalization is one share's price multiplied by the total number of outstanding shares — in other words, what the whole company is worth at the current trading price. It's used to bucket companies by size: mega/large-cap, mid-cap, and small-cap, with smaller companies generally being more volatile.`,
    related:['stock','volatility'] },

  { id:'dividend', cat:'basics', kw:['dividend','dividends','דיבידנד','דיבידנדים'],
    he:`דיבידנד הוא תשלום שחברה מעבירה למחזיקי המניות שלה מתוך הרווחים שלה, בדרך כלל כמה פעמים בשנה. לא כל חברה מחלקת דיבידנד — חברות צמיחה מהירה נוטות להשקיע מחדש את הרווח בעצמן במקום לחלק אותו, בעוד חברות יציבות וגדולות נוטות יותר לחלק דיבידנד קבוע.`,
    en:`A dividend is a payment a company makes to its shareholders out of its profits, usually a few times a year. Not every company pays one — fast-growing companies tend to reinvest profit back into the business instead, while larger, more stable companies more often pay a steady dividend.`,
    related:['dividend-yield','payout-ratio'] },

  { id:'dividend-yield', cat:'basics', kw:['dividend yield','yield','is dividend the same as yield','תשואת דיבידנד','תשואה','האם דיבידנד ותשואה זה אותו דבר'],
    he:`תשואת דיבידנד היא סכום הדיבידנד השנתי חלקי מחיר המניה הנוכחי, באחוזים. היא נותנת דרך להשוות "כמה מקבלים בחזרה בכל שנה רק מהדיבידנד" בין מניות שונות — אבל תשואה גבוהה במיוחד יכולה לפעמים להצביע דווקא על בעיה (למשל מחיר מניה שצנח), ולא רק על הזדמנות. חשוב להבחין: "תשואה" (Return/Yield) הוא מושג רחב בהרבה מדיבידנד — הוא מתאר את הרווח הכולל על השקעה (עלייה במחיר + דיבידנד ששולם, אם היה), בעוד דיבידנד הוא רק אחד המרכיבים האפשריים של תשואה כזו, ולא כל השקעה מניבה דיבידנד בכלל.`,
    en:`Dividend yield is the annual dividend amount divided by the current share price, shown as a percentage. It gives a way to compare "how much you get back each year just from the dividend" across different stocks — but an unusually high yield can sometimes signal trouble (for example a share price that has dropped sharply) rather than simply a good deal. Important distinction: "return" or "yield" in general is a much broader concept than a dividend — it describes the total gain on an investment (price appreciation plus any dividend paid), while a dividend is just one possible component of that return, and not every investment pays a dividend at all.`,
    related:['dividend','payout-ratio'] },

  { id:'ipo', cat:'basics', kw:['ipo','initial public offering','הנפקה','הנפקה ראשונית'],
    he:`הנפקה ראשונית לציבור (IPO) היא הפעם הראשונה שחברה פרטית מוכרת מניות שלה לציבור הרחב ונרשמת למסחר בבורסה. אחרי ה-IPO, כל אחד יכול לקנות ולמכור את המניה בשוק החופשי, בעוד שלפני כן רק משקיעים פרטיים (כמו קרנות הון סיכון) יכלו להחזיק בה.`,
    en:`An initial public offering (IPO) is the first time a private company sells shares to the general public and lists on a stock exchange. After the IPO, anyone can buy and sell the stock on the open market, whereas before it only private investors (like venture-capital funds) could hold it.`,
    related:['exchange','institutional-investors'] },

  { id:'cheap-stock-price-myth', cat:'basics', kw:['is a cheap stock a good deal','cheap stock','low priced stock','is a $5 stock cheaper than a $500 stock','מניה זולה זה טוב','מניה במחיר נמוך','למה לקנות מניה יקרה'],
    he:`מחיר מניה בודד (למשל 5 ש"ח מול 500 ש"ח) לא אומר כמעט כלום על "כמה זולה" החברה — מחיר המניה תלוי גם במספר המניות שהחברה חילקה (Shares Outstanding), שנקבע באופן די שרירותי. חברה עם מניה במחיר 5 ש"ח ו-1,000,000,000 מניות שוות בדיוק כמו חברה עם מניה במחיר 500 ש"ח ו-10,000,000 מניות, אם שווי השוק הכולל (Market Cap) זהה. הדרך הנכונה לבדוק אם מניה "זולה" ביחס לעסק שמאחוריה היא להסתכל על מכפילים כמו P/E או P/S, לא על המחיר הנקוב לבד. מניות "זולות" במחיר נמוך (כמו Penny Stocks) לפעמים דווקא מסוכנות יותר — לרוב נסחרות ככה בגלל שהחברה ביצעה פיצול הפוך (Reverse Split) כדי להימנע מהסרה מהבורסה, או כי היא בקשיים.`,
    en:`A single share price (say $5 versus $500) tells you almost nothing about how "cheap" a company actually is — the share price also depends on how many shares outstanding the company has issued, which is set fairly arbitrarily. A company with a $5 share price and 1 billion shares outstanding is worth exactly the same as one with a $500 share price and 10 million shares, if their total market cap is identical. The correct way to check whether a stock is "cheap" relative to the business behind it is to look at multiples like P/E or P/S, not the sticker price alone. Low-priced "cheap" stocks (like penny stocks) are sometimes actually riskier — they often trade that low because the company did a reverse split to avoid delisting, or because it's in financial trouble.`,
    related:['market-cap','pe-ratio'] },

  { id:'minimum-to-start-investing', cat:'basics', kw:['how much money do i need to start investing','do i need to be rich to invest','minimum amount to invest','fractional shares','כמה כסף צריך כדי להתחיל להשקיע','צריך להיות עשיר כדי להשקיע','צריך להיות עשיר','עשיר כדי להשקיע','מניות שבר'],
    he:`בעבר היה צריך לקנות מניה שלמה לפחות (מה שיכול היה לעלות מאות או אלפי דולרים למניה יקרה), אבל היום ברוקרים רבים מאפשרים לקנות "מניות שבר" (Fractional Shares) — כלומר לקנות למשל ב-50 ש"ח בלבד חלק קטן ממניה של חברה שהמחיר שלה הרבה יותר גבוה. זה הפריך במידה רבה את המיתוס שצריך להיות עשיר כדי להתחיל להשקיע. עם זאת, סכום ההשקעה עדיין משפיע: עמלות קנייה/מכירה קבועות (אם קיימות אצל הברוקר) יכולות "לאכול" אחוז גדול יותר מסכום קטן, ולכן שווה לבדוק את מבנה העמלות של הברוקר לפני שמתחילים.`,
    en:`In the past you had to buy at least one whole share (which could cost hundreds or thousands of dollars for an expensive stock), but today many brokers allow buying "fractional shares" — meaning you can invest as little as $10 to get a small slice of a much more expensive stock. This has largely debunked the myth that you need to be rich to start investing. That said, the amount still matters: flat buy/sell commissions (if the broker charges them) can eat up a much bigger percentage of a small amount, so it's worth checking a broker's fee structure before starting.`,
    related:['broker','dollar-cost-averaging'] },

  { id:'blue-chip', cat:'basics', kw:['blue chip','blue chip stock','blue chips','בלו צ\'יפ','מניית ערך בטוחה','חברת ענק יציבה'],
    he:`Blue Chip (בלו צ'יפ) הוא כינוי למניה של חברה גדולה, יציבה, ותיקה ומוכרת, עם היסטוריה ארוכה של רווחיות ולרוב גם תשלום דיבידנד — למשל חברות כמו קוקה קולה, מיקרוסופט או ג'ונסון אנד ג'ונסון. השם מגיע ממשחק הפוקר, שבו הצ'יפ הכחול הוא בעל הערך הגבוה ביותר. מניות Blue Chip נחשבות בדרך כלל פחות תנודתיות ופחות מסוכנות ממניות צמיחה קטנות וחדשות, אבל זה לא אומר שהן חסינות מירידות — גם חברות ענק יכולות לאבד המון ערך אם המצב העסקי שלהן מתדרדר.`,
    en:`A blue chip stock is a term for a share in a large, stable, well-established, well-known company with a long history of profitability and usually also dividend payments — for example companies like Coca-Cola, Microsoft, or Johnson & Johnson. The name comes from poker, where the blue chip carries the highest value. Blue chip stocks are generally considered less volatile and less risky than small, newer growth stocks, but that doesn't mean they're immune to declines — even giant companies can lose a huge amount of value if their business situation deteriorates.`,
    related:['market-cap','dividend'] },

  { id:'getting-started-investing', cat:'basics', kw:['what should i invest in','where should i put my money','i have some money saved what should i invest in','how do i start investing',"don't want to pick stocks myself what should i do",'יש לי כסף מה כדאי להשקיע בו','במה כדאי להשקיע','איך מתחילים להשקיע','לא רוצה לבחור מניות בעצמי','לא רוצה לבחור מניות','מה כדאי לי לעשות עם הכסף'],
    he:`אין תשובה אחת שמתאימה לכולם — התשובה תלויה בטווח ההשקעה שלך, כמה סיכון אתה מוכן לספוג, ולמה אתה בכלל חוסך (פרישה? דירה בעוד 3 שנים? רק לגדל הון לטווח ארוך?). נקודת התחלה נפוצה ופשוטה למי שלא רוצה לבחור מניות בעצמו היא קרן מחקה רחבה (ETF על מדד כמו S&P 500), שנותנת פיזור מיידי על פני מאות חברות בעלות נמוכה יחסית. חשוב גם: אם יש לך חוב בריבית גבוהה, לרוב עדיף לסגור אותו לפני שמתחילים להשקיע, ורצוי שתהיה קרן חירום נזילה לפני שמכניסים כסף לנכסים תנודתיים. זו סקירה כללית ולא ייעוץ השקעות אישי המותאם למצב הפיננסי הספציפי שלך.`,
    en:`There's no one answer that fits everyone — it depends on your investment horizon, how much risk you're comfortable with, and why you're saving in the first place (retirement? a home in 3 years? just growing wealth long-term?). A common, simple starting point for someone who doesn't want to pick individual stocks is a broad index-tracking ETF (on something like the S&P 500), which gives instant diversification across hundreds of companies at relatively low cost. Also important: if you're carrying high-interest debt, it's usually better to pay that down before investing, and it's wise to have a liquid emergency fund before putting money into volatile assets. This is a general overview, not personalized investment advice tailored to your specific financial situation.`,
    related:['etf','time-horizon'] },

