  { id:'diversification', cat:'risk', kw:['diversification','diversify','פיזור','פיזור סיכונים','דיברסיפיקציה'],
    he:`פיזור השקעות פירושו לא לשים את כל הכסף בנכס אחד, אלא לחלק אותו בין מניות, ענפים, אזורים גיאוגרפיים ואולי גם סוגי נכסים שונים (מניות, אג"ח וכו'). הרעיון: אם נכס אחד יורד בחדות, שאר התיק לא בהכרח יורד באותה מידה, וזה מקטין את התנודתיות הכוללת של התיק. חשוב לדעת: פיזור רחב יותר לא "תמיד עדיף" — הוא מקטין גם את הסיכוי לתשואה יוצאת דופן, לא רק את הסיכון.`,
    en:`Diversification means not putting all your money in one asset, but spreading it across stocks, sectors, geographic regions, and maybe different asset classes (stocks, bonds, etc). The idea: if one asset drops sharply, the rest of the portfolio doesn't necessarily drop by the same amount, which lowers the overall volatility of the portfolio. Worth knowing: broader diversification isn't "always better" — it also reduces the chance of an outsized return, not just the risk.`,
    related:['asset-allocation','correlation'] },

  { id:'risk', cat:'risk', kw:['risk','risk management','סיכון','ניהול סיכונים'],
    he:`סיכון בשוק ההון פירושו הסיכוי שההשקעה תרד בערכה, ולא רק תעלה. אין דרך להשקיע בלי סיכון כלשהו — אבל אפשר לנהל אותו: פיזור בין נכסים שונים, לא להשקיע כסף שצריך בטווח קצר, גודל פוזיציה סביר (Position Sizing), וקביעת "סטופ לוס" (מחיר שבו יוצאים מהעסקה כדי להגביל הפסד) הם כלים נפוצים.`,
    en:`Risk in the market means the chance an investment loses value, not just gains it. There's no way to invest with zero risk — but it can be managed: diversifying across different assets, not investing money you need in the short term, reasonable position sizing, and setting a "stop loss" (a price at which you exit the position to cap the loss) are common tools.`,
    related:['risk-reward-ratio','position-sizing'] },

  { id:'beta', cat:'risk', kw:['beta','stock beta','בטא'],
    he:`בטא מודדת כמה תנודתית מניה ביחס לשוק הכללי (לרוב מול מדד כמו S&P 500, שהבטא שלו מוגדרת כ-1). בטא של 1.5 אומרת בגדול שכשהשוק זז 1%, המניה נוטה לזוז בערך 1.5% (לשני הכיוונים); בטא של 0.5 אומרת שהיא נוטה לזוז פחות מהשוק. בטא גבוהה משמעה תנודתיות גבוהה יותר ביחס לשוק — לא בהכרח סיכון "רע", אבל בהחלט סיכון גדול יותר.`,
    en:`Beta measures how volatile a stock is relative to the overall market (usually versus an index like the S&P 500, whose beta is defined as 1). A beta of 1.5 roughly means that when the market moves 1%, the stock tends to move about 1.5% (in either direction); a beta of 0.5 means it tends to move less than the market. High beta means higher volatility relative to the market — not necessarily "bad" risk, but definitely bigger risk.`,
    related:['volatility','correlation'] },

  { id:'correlation', cat:'risk', kw:['correlation','correlated assets','קורלציה','מתאם'],
    he:`קורלציה מודדת עד כמה שני נכסים נוטים לזוז יחד. קורלציה של 1 אומרת שהם זזים בדיוק יחד; קורלציה של 1- אומרת שהם זזים בכיוונים הפוכים; קורלציה קרובה ל-0 אומרת שאין קשר ברור בין התנועות שלהם. פיזור אמיתי דורש נכסים עם קורלציה נמוכה זה לזה — להחזיק 10 מניות טכנולוגיה שונות זה פחות "מפוזר" ממה שזה נראה, כי הן נוטות לזוז ביחד.`,
    en:`Correlation measures how much two assets tend to move together. A correlation of 1 means they move exactly together; -1 means they move in opposite directions; close to 0 means there's no clear relationship between their movements. Real diversification requires assets with low correlation to each other — holding 10 different tech stocks is less "diversified" than it looks, because they tend to move together.`,
    related:['diversification','beta'] },

  { id:'drawdown', cat:'risk', kw:['drawdown','max drawdown','ירידה מקסימלית','דרודאון','דראודאון'],
    he:`Drawdown הוא הירידה באחוזים משיא קודם לשפל שאחריו, לפני שהמחיר (או שווי התיק) חוזר לעלות. Max Drawdown הוא הירידה הגדולה ביותר שקרתה בתקופה נתונה — מדד חשוב מאוד להבנת "כמה כאב" משקיע היה צריך לספוג בדרך, גם אם התשואה הסופית לטווח ארוך הייתה טובה.`,
    en:`Drawdown is the percentage decline from a prior peak to the low point that follows, before the price (or portfolio value) recovers. Max drawdown is the largest such decline that occurred over a given period — a very important measure for understanding "how much pain" an investor had to endure along the way, even if the eventual long-term return was good.`,
    related:['risk','volatility'] },

  { id:'risk-reward-ratio', cat:'risk', kw:['risk reward','risk/reward ratio','risk to reward','יחס סיכוי סיכון'],
    he:`יחס סיכוי-סיכון משווה כמה אפשר להרוויח בעסקה מול כמה אפשר להפסיד בה, לפני שנכנסים אליה. למשל, אם הסטופ לוס במרחק 2% מהכניסה והיעד במרחק 6%, יחס הסיכוי-סיכון הוא 1:3. גם עם אחוז הצלחה נמוך יחסית, יחס סיכוי-סיכון טוב לאורך זמן יכול עדיין להיות רווחי במצטבר.`,
    en:`The risk/reward ratio compares how much you could gain on a trade versus how much you could lose, before entering it. For example, if the stop-loss is 2% away from entry and the target is 6% away, the risk/reward ratio is 1:3. Even with a relatively low win rate, a good risk/reward ratio maintained over time can still be profitable in aggregate.`,
    related:['position-sizing','order-types'] },

  { id:'position-sizing', cat:'risk', kw:['position sizing','position size','גודל פוזיציה'],
    he:`גודל פוזיציה (Position Sizing) הוא ההחלטה כמה כסף להשקיע בעסקה בודדת ביחס לגודל התיק הכולל. כלל נפוץ בקרב סוחרים: לא לסכן יותר מאחוז קטן (למשל 1-2%) מהתיק הכולל בעסקה בודדת — כך שגם רצף הפסדים לא מוחק את התיק, ומשקיעים יכולים "לשרוד" תקופות רעות ולהמשיך לפעול.`,
    en:`Position sizing is the decision of how much money to put into a single trade relative to the overall portfolio size. A common rule among traders: don't risk more than a small percentage (for example 1-2%) of the total portfolio on a single trade — so that even a losing streak doesn't wipe out the portfolio, and investors can "survive" bad stretches and keep operating.`,
    related:['risk-reward-ratio','risk'] },

  { id:'asset-allocation', cat:'risk', kw:['asset allocation','חלוקת נכסים','הקצאת נכסים','אסט אלוקיישן'],
    he:`הקצאת נכסים היא ההחלטה כמה מהתיק להשקיע במניות, כמה באג"ח, וכמה אולי במזומן או נכסים אחרים. זו לרוב ההחלטה עם ההשפעה הגדולה ביותר על סיכון ותשואה של תיק לטווח ארוך — יותר אפילו מבחירת המניות הספציפיות — ותלויה בטווח הזמן ובסובלנות לסיכון של המשקיע.`,
    en:`Asset allocation is the decision of how much of a portfolio to put into stocks, how much into bonds, and how much perhaps into cash or other assets. It's often the single biggest driver of a portfolio's long-term risk and return — even more than picking specific stocks — and depends on the investor's time horizon and risk tolerance.`,
    related:['diversification','time-horizon'] },

  { id:'rebalancing', cat:'risk', kw:['rebalancing','rebalance portfolio','איזון מחדש','ריבלנסינג','ריבאלנס'],
    he:`איזון מחדש הוא החזרת התיק לחלוקת הנכסים המקורית שהוגדרה מראש, אחרי שהשוק "עיוות" אותה — למשל אם מניות עלו הרבה, הן עשויות להוות פתאום נתח גדול מדי מהתיק ביחס לתוכנית המקורית, ואיזון מחדש אומר למכור חלק מהן ולקנות אג"ח כדי לחזור ליחס המקורי.`,
    en:`Rebalancing is bringing the portfolio back to its originally intended asset mix after the market has "distorted" it — for example if stocks have rallied a lot, they might suddenly make up too large a share of the portfolio relative to the original plan, and rebalancing means selling some of them and buying bonds to return to the original ratio.`,
    related:['asset-allocation','diversification'] },

  { id:'time-horizon', cat:'risk', kw:['time horizon','investment horizon','should a one day drop worry a long term investor','טווח השקעה','ירידה של יום אחד','משקיע לטווח ארוך צריך לדאוג'],
    he:`טווח השקעה הוא כמה זמן מתכננים להחזיק בהשקעה לפני שצריך את הכסף בפועל. טווח ארוך (עשור ומעלה) בדרך כלל מאפשר לספוג יותר תנודתיות בדרך, כי יש זמן להתאושש מירידות; טווח קצר דורש בדרך כלל זהירות רבה יותר ופחות חשיפה לנכסים תנודתיים. משתמע מכך: אם ההשקעה שלך היא לטווח ארוך, ירידה של יום אחד או שבוע אחד היא בדרך כלל "רעש" קצר טווח שלא אמור לשנות את התוכנית — השאלה הרלוונטית היא לא "מה קרה היום" אלא האם משהו מהותי השתנה בעסק או בתזה המקורית שבגללה נכנסת להשקעה.`,
    en:`Time horizon is how long you plan to hold an investment before you actually need the money. A long horizon (a decade or more) generally allows for absorbing more volatility along the way, since there's time to recover from declines; a short horizon generally calls for more caution and less exposure to volatile assets. The implication: if your investment is long-term, a one-day or one-week decline is usually short-term "noise" that shouldn't change the plan — the relevant question isn't "what happened today" but whether anything fundamental changed about the business or the original reason you invested.`,
    related:['asset-allocation','dollar-cost-averaging'] },

  { id:'market-timing', cat:'risk', kw:['market timing','time the market','timing the market','is timing the market a good strategy','can you time the market','תזמון השוק','לתזמן את השוק','לתזמן את השוק כדי להרוויח'],
    he:`תזמון שוק (Market Timing) הוא הניסיון לחזות מתי בדיוק השוק ייגע בשפל או בשיא, כדי לקנות ולמכור בדיוק ברגעים הנכונים. כמעט כל המחקר האקדמי והניסיון המעשי מראים שזה קשה באופן קיצוני לעשות בעקביות לאורך זמן — אפילו מנהלי קרנות מקצועיים מתקשים בכך. הבעיה המרכזית: אם מפספסים רק כמה מהימים הכי טובים של השוק (שלרוב מגיעים דווקא סמוך לתקופות ירידה חדה), התשואה הכוללת לאורך שנים נפגעת משמעותית. אסטרטגיות כמו השקעה קבועה לאורך זמן (Dollar Cost Averaging) הן לרוב חלופה מעשית יותר מניסיון "לתפוס" את הרגע המושלם.`,
    en:`Market timing is the attempt to predict exactly when the market will hit a bottom or a top, in order to buy and sell at precisely the right moments. Nearly all academic research and practical experience shows this is extremely hard to do consistently over time — even professional fund managers struggle with it. The core problem: missing just a handful of the market's best days (which often happen right around periods of sharp decline) meaningfully hurts total returns over the years. Strategies like investing a fixed amount regularly over time (dollar-cost averaging) are usually a more practical alternative than trying to "catch" the perfect moment.`,
    related:['dollar-cost-averaging','lump-sum'] },

  { id:'investing-idioms', cat:'risk', kw:['buy the dip','blood in the streets','never catch a falling knife','falling knife','diamond hands','fomo','fomo in investing','stonks','stocks only go up','get rich quick','number go up','לקנות בירידה','דם ברחובות','אל תתפוס סכין נופלת','ידיים של יהלום','פומו','סטונקס','להתעשר מהיום למחר','להתעשר מהר בבורסה','אתעשר מהיום למחר','מהיום למחר בבורסה'],
    he:`כמה ביטויים וסלנג נפוצים בעולם ההשקעות: "Buy the Dip" (לקנות בירידה) — לקנות דווקא כשהמחיר יורד, מתוך אמונה שזו ירידה זמנית; מסוכן אם הירידה בעצם משקפת בעיה אמיתית בעסק. "דם ברחובות" (Blood in the Streets) — ביטוי (מיוחס לרוטשילד) שאומר שהזמן הכי טוב לקנות הוא דווקא כשכולם בפאניקה ומוכרים — גישה מנוגדת (Contrarian). "אל תתפוס סכין נופלת" (Never Catch a Falling Knife) — אזהרה הפוכה: אל תקנה נכס שנמצא באמצע נפילה חדה רק כי הוא "כבר ירד הרבה", כי הוא עוד יכול לרדת הרבה יותר. "Diamond Hands" (ידיים של יהלום) — סלנג (במיוחד ממניות המים כמו GameStop) שמתאר מחזיק שמסרב למכור למרות תנודתיות קיצונית, לפעמים כתג כבוד ולפעמים כהתנהגות לא רציונלית. FOMO (Fear Of Missing Out) — הפחד לפספס עלייה, שגורם לאנשים לקנות בפזיזות בשיא ההתלהבות דווקא כשהמחיר כבר גבוה. חשוב לזכור: אלה סיסמאות פופולריות ולא כללי השקעה — כל אחת מהן יכולה להיות נכונה או שגויה תלוי בהקשר הספציפי. "Stonks" הוא סלנג אינטרנטי (במקור בדיחה/מם) למניות, שמלווה לעיתים קרובות את התפיסה השגויה ש"המניות רק עולות" — תפיסה מסוכנת, כי שוק שעולה הרבה זמן ברציפות הוא לא הבטחה שהוא ימשיך לעלות. חשוב גם לזכור: "להתעשר מהיום למחר" בבורסה הוא בדרך כלל פנטזיה ולא אסטרטגיה — עושר לרוב נבנה בהשקעה עקבית וסבלנית לאורך שנים, לא בקפיצה אחת.`,
    en:`A few common idioms and slang terms in investing: "Buy the dip" — buying specifically when the price falls, on the belief it's a temporary decline; risky if the decline actually reflects a real problem with the business. "Blood in the streets" (attributed to Rothschild) — the idea that the best time to buy is exactly when everyone is panicking and selling — a contrarian approach. "Never catch a falling knife" — the opposite warning: don't buy an asset in the middle of a sharp decline just because it's "already fallen a lot," since it can keep falling much further. "Diamond hands" — slang (especially from meme stocks like GameStop) describing a holder who refuses to sell despite extreme volatility, sometimes worn as a badge of honor and sometimes just irrational stubbornness. FOMO (Fear Of Missing Out) — the fear of missing a rally, which causes people to buy impulsively right at peak excitement, exactly when the price is already high. Important to remember: these are popular catchphrases, not investing rules — each one can be right or wrong depending on the specific context. "Stonks" is internet slang (originally a joke/meme) for stocks, often paired with the mistaken belief that "stocks only go up" — a dangerous assumption, since a market that has risen for a long stretch is no guarantee it will keep rising. Also worth remembering: "getting rich overnight" in the market is generally a fantasy, not a strategy — real wealth is usually built through patient, consistent investing over years, not one lucky jump.`,
    related:['pullback','volatility'] },

  { id:'compound-interest', cat:'risk', kw:['compound interest','compounding','compound','rule of 72','when should i start saving for retirement','how much money do i need to retire','ריבית דריבית','כלל 72','מתי כדאי להתחיל לחסוך לפרישה','כמה כסף אני צריך כדי לפרוש','איך כדאי לתכנן לפרישה','לחסוך לפרישה','is it realistic to retire at','want to retire at'],
    he:`ריבית דריבית פירושה שהתשואה שמרוויחים משקיעה מחדש ומרוויחה בעצמה תשואה נוספת עם הזמן — כך שהצמיחה מואצת ולא ליניארית. ההשפעה שלה קטנה בשנים הראשונות אבל הופכת משמעותית מאוד לאורך זמן ארוך, ולכן היא אחד הארגומנטים המרכזיים בעד התחלה מוקדמת של השקעה, כולל לפרישה — מי שמתחיל לחסוך בגיל 25 צריך להפקיד הרבה פחות כסף בסך הכול כדי להגיע לאותה תוצאה כמו מי שמתחיל בגיל 40, בזכות שנים נוספות של צמיחה מצטברת. "כלל ה-72" (Rule of 72) הוא קיצור דרך מהיר להערכה: מחלקים 72 בשיעור התשואה השנתי (באחוזים) כדי לקבל בקירוב כמה שנים ייקח לכסף להכפיל את עצמו — למשל בתשואה של 8% בשנה, הכסף יוכפל בערך תוך 9 שנים (72/8). אין תשובה אחידה ל"כמה כסף צריך כדי לפרוש" — זה תלוי בהוצאות הצפויות, בגיל הפרישה הרצוי, ובמקורות הכנסה נוספים (כמו קצבת ביטוח לאומי או פנסיה) — זו תוכנית אישית ולא נוסחה כללית.`,
    en:`Compound interest means the return you earn gets reinvested and itself earns additional return over time — so growth accelerates rather than staying linear. Its effect is small in the early years but becomes very significant over a long period, which is why it's one of the main arguments for starting to invest early, including for retirement — someone who starts saving at 25 needs to contribute far less money in total to reach the same result as someone starting at 40, thanks to extra years of compounding. The "Rule of 72" is a quick mental shortcut: divide 72 by the annual return rate (as a percentage) to roughly estimate how many years it takes money to double — for example at an 8% annual return, money roughly doubles in about 9 years (72/8). There's no single answer to "how much money do I need to retire" — it depends on expected expenses, desired retirement age, and other income sources (like social security or a pension) — it's a personal plan, not a universal formula.`,
    related:['dollar-cost-averaging','time-horizon'] },

  { id:'dollar-cost-averaging', cat:'risk', kw:['dollar cost averaging','dca','השקעה קבועה חודשית','ממוצע עלות דולרי','להשקיע בהדרגה','פריסה לאורך זמן'],
    he:`Dollar Cost Averaging (DCA) פירושו להשקיע סכום קבוע באופן קבוע (למשל חודשי), בלי קשר למחיר הנוכחי בשוק — במקום לנסות "לתזמן" את השוק. כשהמחיר נמוך קונים יותר יחידות, כשהמחיר גבוה קונים פחות, וכך המחיר הממוצע לאורך זמן מתמצע. זו אסטרטגיה פופולרית בעיקר כי היא מסירה את הצורך לנחש מתי "הזמן הנכון" להיכנס.`,
    en:`Dollar cost averaging (DCA) means investing a fixed amount on a regular schedule (for example monthly), regardless of the current market price — instead of trying to "time" the market. When the price is low you buy more units, when it's high you buy fewer, so the average price smooths out over time. It's a popular strategy mainly because it removes the need to guess the "right time" to get in.`,
    related:['lump-sum','time-horizon'] },

  { id:'lump-sum', cat:'risk', kw:['lump sum investing','lump sum','all at once or gradually','invest it all at once','השקעה חד פעמית','בבת אחת או בהדרגה','להשקיע הכל בבת אחת','הכל בבת אחת','בבת אחת','בהדרגה'],
    he:`השקעה חד-פעמית (Lump Sum) פירושה להכניס את כל הסכום לשוק בבת אחת, במקום לפרוס אותו לאורך זמן. מבחינה סטטיסטית, מכיוון שהשוק עולה בממוצע רוב הזמן, השקעה חד-פעמית מיד נוטה להניב תוצאה טובה יותר מ-DCA לאורך תקופות ארוכות — אבל DCA נותן שקט נפשי גדול יותר ופחות סיכון "לתזמון גרוע" של כניסה ממש לפני ירידה חדה.`,
    en:`Lump sum investing means putting the entire amount into the market all at once, rather than spreading it out over time. Statistically, because markets rise on average most of the time, investing a lump sum immediately tends to outperform DCA over long periods — but DCA offers more peace of mind and less risk of unlucky timing right before a sharp decline.`,
    related:['dollar-cost-averaging','time-horizon'] },

