// ---------------------------------------------------------------------------
// Israel-specific market topics. Added after research showed these are
// among the most frequently asked real-world questions for a Hebrew-first
// audience (capital gains tax, tax-advantaged savings vehicles), yet were
// completely absent from the KB.
// ---------------------------------------------------------------------------
const KB_ISRAEL = [
  { id:'capital-gains-tax-israel', cat:'israel', kw:['capital gains tax','tax on stocks','tax on capital gains','how much tax do i pay on stocks','מס רווחי הון','מס רווח הון','כמה מס משלמים על מניות','מס על מכירת מניות','מס על רווחים בבורסה','כמה מס משלמים על רווחים','מיסוי רווחי הון','מס על השקעות','לקזז הפסדים','קיזוז הפסדי הון'],
    he:`בישראל, רווח הון ממכירת ניירות ערך (מניות, קרנות, אג"ח סחיר וכו') ממוסה בדרך כלל ב-25% מהרווח הריאלי (כלומר אחרי ניכוי אינפלציה) עבור יחיד שאינו "בעל מניות מהותי". איגרות חוב שקליות לא צמודות ומק"מ ממוסות ב-15% מהרווח הנומינלי. חשוב: המס משולם רק במועד המכירה בפועל — כל עוד הרווח "על הנייר" ולא מומש, אין חבות מס. הברוקר בדרך כלל מנכה את המס אוטומטית בעת המכירה, כך שברוב המקרים אין צורך בדיווח ידני. אפשר לקזז הפסד הון מול רווח הון באותה שנת מס (אם מכרת מניה אחת בהפסד ואחרת ברווח, משלמים מס רק על ההפרש נטו), ואפשר להעביר הפסדים שלא קוזזו לשנים הבאות ללא הגבלת זמן — אבל אי אפשר להעביר רווחים קדימה. זו סקירה כללית ולא ייעוץ מס אישי — לפרטים על המצב הספציפי שלך כדאי להתייעץ עם רואה חשבון.`,
    en:`In Israel, capital gains from selling securities (stocks, funds, tradable bonds, etc.) are generally taxed at 25% of the real (inflation-adjusted) gain for an individual who isn't a "significant shareholder." Non-indexed shekel bonds and treasury bills (Makam) are taxed at 15% of the nominal gain. Importantly, the tax is only paid when a position is actually sold — as long as a gain is only "on paper" and unrealized, there's no tax liability. The broker typically withholds the tax automatically at the point of sale, so in most cases no manual filing is needed. You can offset a capital loss against a capital gain within the same tax year (if you sold one stock at a loss and another at a profit, you only pay tax on the net difference), and unused losses can be carried forward to future years indefinitely — but gains cannot be carried forward. This is a general overview, not personal tax advice — for your specific situation it's worth consulting an accountant.`,
    related:['dividend','etf'] },

  { id:'mutual-fund-vs-etf', cat:'israel', kw:['mutual fund','difference between mutual fund and etf','etf vs mutual fund','mutual fund vs etf','which has lower fees etf or mutual fund','קרן נאמנות','ההבדל בין קרן נאמנות לתעודת סל','ההבדל בין קרן נאמנות לetf','מסלול מחקה','קרן מחקה'],
    he:`קרן נאמנות (Mutual Fund) וקרן סל/תעודת סל (ETF) שתיהן "אוספות" הרבה משקיעים לתוך סל השקעות אחד משותף, אבל יש הבדלים מעשיים: קרן נאמנות בישראל נקנית ונמכרת פעם ביום לפי שווי נכסי נטו (NAV) שמתעדכן בסוף היום, ואילו ETF (וגם תעודת סל הישראלית המקבילה) נסחר על גבי הבורסה במהלך כל שעות המסחר בדיוק כמו מניה רגילה, עם מחיר שמשתנה כל הזמן. קרנות נאמנות יכולות להיות "מחקות" (עוקבות אחרי מדד, כמו S&P 500) או "מנוהלות אקטיבית" (מנהל שבוחר ניירות ערך בעצמו), כאשר בממוצע לאורך זמן קרנות מנוהלות רבות מתקשות להכות את המדד אחרי דמי הניהול. דמי הניהול של קרן מחקה או ETF נוטים להיות נמוכים משמעותית מקרן מנוהלת אקטיבית.`,
    en:`A mutual fund and an ETF (or its Israeli equivalent, a "tracker certificate") both pool many investors into one shared basket of investments, but there are practical differences: a mutual fund in Israel is bought and sold once a day at its net asset value (NAV), calculated at day's end, while an ETF trades on the stock exchange throughout market hours just like a regular stock, with a price that changes constantly. Mutual funds can be "tracking" (passively following an index, like the S&P 500) or "actively managed" (a manager picks the holdings), and on average over time many actively managed funds struggle to beat the index after fees. Management fees for a tracking fund or ETF tend to be significantly lower than for an actively managed fund.`,
    related:['etf','index-investing-vs-stockpicking'] },

  { id:'tax-advantaged-savings-israel', cat:'israel', kw:['קרן השתלמות','קופת גמל להשקעה','פטור ממס על תשואה','pension fund israel','קרן פנסיה'],
    he:`בישראל יש כלי חיסכון שנהנים מהטבות מס בהשוואה להשקעה "רגילה" בחשבון מסחר: קרן השתלמות (בדרך כלל דרך מעסיק, עם הפקדה של העובד והמעסיק) פטורה ממס רווח הון על הצבירה בתנאים מסוימים — בעיקר אם שומרים אותה 6 שנים ומעלה בלי למשוך, או משתמשים בה למטרות לימוד מוכרות. קופת גמל להשקעה היא כלי דומה בעיקרון, פתוח גם לעצמאים ולמי שאין לו קרן השתלמות דרך עבודה, עם אפשרות למשוך כקצבה פטורה ממס בגיל פרישה. קרן פנסיה היא כלי חיסכון לטווח ארוך לפנסיה, עם הטבות מס משמעותיות בהפקדה עצמה (ולא רק בתשואה). ההבדל המרכזי מול השקעה ישירה במניות/ETF בחשבון מסחר רגיל: פחות גמישות (הגבלות משיכה או קנסות), אבל יתרון מס משמעותי אם עומדים בתנאים.`,
    en:`Israel has several savings vehicles that carry tax advantages compared to investing "normally" through a regular brokerage account. A "keren hishtalmut" (study fund, usually via an employer, funded by both employee and employer contributions) is exempt from capital gains tax on its growth under certain conditions — mainly if left untouched for 6+ years, or used for recognized educational purposes. A "kupat gemel le'hashkaa" (investment provident fund) is a similar tool in principle, also open to the self-employed and anyone without an employer-based study fund, with an option to withdraw it as a tax-exempt annuity at retirement age. A pension fund is a long-term retirement savings vehicle with significant tax benefits on the contribution itself (not just on the returns). The main tradeoff versus investing directly in stocks/ETFs through a regular brokerage account: less flexibility (withdrawal restrictions or penalties), but a meaningful tax advantage if the conditions are met.`,
    related:['capital-gains-tax-israel','compound-interest'] },
];
KB.push.apply(KB, KB_ISRAEL);
