// ---------------------------------------------------------------------------
// Gaps found during real-device QA (screenshots from the live site). Each of
// these was a question a real user actually asked that fell through to the
// generic fallback or matched an unrelated entry.
// ---------------------------------------------------------------------------
const KB_QA_GAPS = [
  { id:'bull-vs-bear-market', cat:'comparisons', sides:['bull-market','bear-market'], kw:['bull market vs bear market','difference between bull and bear market','bull and bear market','ההבדל בין שוק שורי לשוק דובי','שוק שורי לשוק דובי','שוק דובי לשורי','שוק שורי לדובי','בול מרקט ובר מרקט'],
    he:`"שוק שורי" (Bull Market) הוא תקופה ממושכת שבה מחירים עולים באופן כללי, בדרך כלל מוגדר כעלייה של 20% ומעלה משפל קודם, ומלווה באופטימיות, ביטחון של משקיעים וכלכלה מתרחבת. "שוק דובי" (Bear Market) הוא ההפך: ירידה של 20% ומעלה משיא קודם, לרוב מלווה בפסימיות, חשש ולעיתים האטה כלכלית. מקור השמות בדרך שבה החיות תוקפות: שור נועץ קרניים כלפי מעלה, ודוב מנחית טפרים כלפי מטה. חשוב לדעת: שוק דובי הוא חלק נורמלי ומחזורי מהשוק ולא אירוע חריג — היסטורית, שווקים דוביים היו קצרים יותר משווקים שוריים, ואחריהם השוק בסופו של דבר התאושש, אם כי אין ערובה לכך שזה יקרה שוב או תוך כמה זמן. ירידה קטנה יותר (כ-10%) נקראת "תיקון" (Correction) ולא שוק דובי.`,
    en:`A "bull market" is an extended period of generally rising prices, usually defined as a 20%+ rise from a prior low, accompanied by optimism, investor confidence, and an expanding economy. A "bear market" is the opposite: a 20%+ decline from a prior peak, typically accompanied by pessimism, fear, and sometimes an economic slowdown. The names come from how the animals attack: a bull thrusts its horns upward, a bear swipes its claws downward. Worth knowing: a bear market is a normal, cyclical part of markets rather than a freak event — historically, bear markets have been shorter than bull markets, and markets have eventually recovered afterward, though there's no guarantee that repeats or how long it would take. A smaller decline (around 10%) is called a "correction," not a bear market.`,
    related:['trend','pullback'] },

  { id:'what-to-do-in-a-market-drop', cat:'risk', kw:['what should i do if the market drops','market dropped 20% what do i do','should i sell when the market falls','what to do in a crash','אם השוק ירד','השוק ירד','מה כדאי לעשות','מה לעשות כשהשוק יורד','מה כדאי לי לעשות כשהשוק יורד','השוק קורס מה לעשות','מה עושים כשהשוק יורד'],
    he:`אין תשובה אחת נכונה, אבל יש כמה עקרונות שחוזרים בחומרי חינוך פיננסי: ראשית, ירידה חדה היא חלק צפוי ונורמלי מהשקעה במניות — לא סימן שמשהו "נשבר". שנית, השאלה החשובה היא לא "מה קרה השבוע" אלא האם משהו מהותי השתנה בתזה המקורית שלך או בטווח הזמן שלך. אם הכסף מיועד לעוד 15 שנה, ירידה של 20% היום היא בעיקר רעש; אם אתה צריך אותו בעוד שנה, ייתכן שהתמהיל לא התאים מלכתחילה לטווח הקצר. שלישית, מכירה בפאניקה אחרי ירידה היא הדרך להפוך הפסד "על הנייר" להפסד ממומש — וגם מקשה לחזור, כי הימים הטובים של השוק מגיעים לרוב דווקא סמוך לתקופות הגרועות. רביעית, עבור חלק מהמשקיעים ירידה היא דווקא הזדמנות להמשיך להפקיד באופן קבוע (DCA) במחירים נמוכים יותר. חשוב: זו סקירה חינוכית כללית ולא ייעוץ השקעות אישי, ואם ירידה גורמת לך מצוקה אמיתית — ייתכן שרמת הסיכון בתיק גבוהה מדי עבורך, וזו שאלה ששווה לבחון עם איש מקצוע.`,
    en:`There's no single right answer, but a few principles recur across financial-education material: first, a sharp decline is an expected, normal part of investing in stocks — not a sign something is "broken." Second, the important question isn't "what happened this week" but whether anything fundamental changed in your original thesis or your time horizon. If the money is for 15 years from now, a 20% drop today is mostly noise; if you need it in a year, the allocation may not have suited that short horizon in the first place. Third, panic-selling after a decline is how a paper loss becomes a realized one — and it also makes getting back in harder, since the market's best days often cluster right around its worst. Fourth, for some investors a decline is actually an opportunity to keep contributing regularly (DCA) at lower prices. Important: this is general educational context, not personal investment advice, and if a decline is causing you real distress, your portfolio's risk level may be too high for you — a question worth reviewing with a professional.`,
    related:['behavioral-biases','dollar-cost-averaging'] },

  { id:'how-to-evaluate-a-company', cat:'fundamentals', kw:['reasons to invest in a company','reasons not to invest in a company','pros and cons of investing in a company','how do i decide whether to invest in a company','how to evaluate a company','סיבות להשקיע בחברה','סיבות לא להשקיע','סיבות למה לא להשקיע','השקעה בחברה','איך לבדוק אם כדאי להשקיע בחברה','איך מעריכים חברה','יתרונות וחסרונות של השקעה בחברה'],
    he:`אין רשימה אוניברסלית, אבל אלה השיקולים שחוזרים שוב ושוב כשבוחנים חברה מסוימת. סימנים שנחשבים חיוביים: (1) יתרון תחרותי בר-קיימא ("מואט") שמקשה על מתחרים לחקות; (2) צמיחה עקבית בהכנסות וברווח, לא רק ברבעון בודד; (3) מאזן בריא — חוב נשלט ותזרים מזומנים חופשי חיובי; (4) תשואה גבוהה על ההון המושקע (ROIC/ROE), שמעידה שהחברה מייצרת ערך אמיתי מהכסף שלה; (5) הנהלה עם רקורד סביר בהקצאת הון. סימני אזהרה: (1) חוב גבוה במיוחד ביחס לענף, במיוחד בסביבת ריבית עולה; (2) הסתמכות על לקוח, מוצר או שוק יחיד; (3) שחיקה מתמשכת בשולי הרווח; (4) מכפיל גבוה מאוד שכבר מגלם ציפיות אופטימיות מאוד — כלומר מעט מקום לטעות; (5) דילול מתמשך של בעלי המניות (הנפקת מניות חדשות); (6) ענף בדעיכה מבנית או רגולציה מאיימת. חשוב: זו מסגרת חשיבה חינוכית כללית — היא לא מחליפה בדיקה של המספרים בפועל בדוחות החברה, ואינה ייעוץ השקעות לגבי חברה ספציפית.`,
    en:`There's no universal checklist, but these are the considerations that come up repeatedly when examining a specific company. Signs generally viewed positively: (1) a durable competitive advantage (a "moat") that makes it hard for rivals to copy; (2) consistent growth in revenue and profit, not just one strong quarter; (3) a healthy balance sheet — manageable debt and positive free cash flow; (4) a high return on invested capital (ROIC/ROE), indicating the company generates real value from its money; (5) management with a reasonable track record of capital allocation. Warning signs: (1) unusually high debt relative to its industry, especially in a rising-rate environment; (2) dependence on a single customer, product, or market; (3) persistently eroding profit margins; (4) a very high multiple that already prices in very optimistic expectations — meaning little room for error; (5) ongoing shareholder dilution (issuing new shares); (6) a structurally declining industry or looming regulation. Important: this is a general educational framework — it doesn't replace examining the actual numbers in the company's filings, and it isn't investment advice about any specific company.`,
    related:['fundamental','moat'] },
];
KB.push.apply(KB, KB_QA_GAPS);
